const data = {
  products: [
    {
      name: 'BLACK+DECKER BEH200-QS Taladro percutor con cable 500W, 230V, incluye empuñadura lateral, 500 W',
      category: 'Taladro Percutor',
      slug: 'black+decker-BEH200-QS',
      link: 'https://www.amazon.es/BEH200-QS-Taladro-percutor-incluye-empu%C3%B1adura/dp/B07MJHBCKX?_encoding=UTF8&refRID=D4KSTNHTV7FYJY985F44&th=1&linkCode=ll1&tag=sarria93-21&linkId=5ab6ae49febad0a88fd6613ea80c6340&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/taladrosPercutor/81LuqiWs53L._AC_SL1500_.jpg',
      price: 29.5,
      brand: 'Black+Decker',
      rating: 4.5,
      numReviews: 4059,
      countInStock: 24,
      description: [
        'Taladro percutor con cable de 500 W y portabrocas sin llave de 13 mm',
        'Acción percutora de 49.300 imp. adecuado para perforar en mampostería',
        'Sistema reversible y botón de bloqueo para mayor ergonomía y comodidad',
        'El motor de velocidad variable de 0-2.900 rpm proporciona un arranque controlado y preciso',
        'Incluye empuñadura lateral',
      ],
    },
    {
      name: 'Bosch EasyImpact 550 - Taladro percutor (550 W, empuñadura adicional, tope de profundidad, maletín)',
      category: 'Taladro Percutor',
      slug: 'Bosch-EasyImpact-550-Taladro-percutor',
      link: 'https://www.amazon.es/Bosch-EasyImpact-empu%C3%B1adura-adicional-profundidad/dp/B06XR17QSM?_encoding=UTF8&refRID=D4KSTNHTV7FYJY985F44&th=1&linkCode=ll1&tag=sarria93-21&linkId=a2990c4a0c49adf5a1a6d0bff4380ca5&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/taladrosPercutor/61uJKO20ZkL._AC_SL1024_.jpg',
      price: 39.55,
      brand: 'Bosch Home and Garden',
      rating: 4.6,
      numReviews: 4015,
      countInStock: 29,
      description: [
        'Potente y compacta herramienta que facilita los trabajos de perforación',
        'Perforar nunca fue tan sencillo: gracias a su bajo peso y su compacto y ergonómico diseño, el manejo de la herramienta resulta especialmente cómodo y sencillo',
        'Potencia de perforación elevada a pesar de la construcción compacta, con independencia del material, incluso en hormigón',
        'Portabrocas de sujeción rápida de dos casquillos para cambio de herramienta sencillo',
        'Control electrónico del número de revoluciones Bosch: la «aceleración» de 50 al máximo con el pulsador de conmutación le permite trabajar de forma precisa, por ejemplo, al inicio de la perforación de superficies lisas o en trabajos de atornillado',
        'Compatible con el Drill Assistant de Bosch para un trabajo aún más preciso: determinación sencilla de la profundidad de perforación y trabajo sin polvo (opcionalmente, disponible como accesorio)',
      ],
    },
    {
      name: 'Martillo Percutor, Martillo Perforador, 5J Energía de Impacto, SDS Plus Mandril, 4 Funciones en 1 con Embrague de Seguridad, Utilizado para Concreto, Metal y Piedra - TRH02A',
      category: 'Taladro Percutor',
      slug: 'Martillo-Percutor-TRH02A',
      link: 'https://www.amazon.es/Martillo-Perforador-Funciones-Seguridad-Utilizado/dp/B097YFX623?_encoding=UTF8&psc=1&refRID=D4KSTNHTV7FYJY985F44&linkCode=ll1&tag=sarria93-21&linkId=879ab7b0c5fb85a7472ea23b81736fd7&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/taladrosPercutor/71mLxSjsn9S._AC_SL1500_.jpg',
      price: 69.99,
      brand: 'TACK',
      rating: 3.4,
      numReviews: 7,
      countInStock: 50,
      description: [
        '[Potente Motor]: El martillo perforador cuenta con un motor de 1050 W, 5J energía de impacto que se puede proporcionar fuerza de propulsión y hacer agujeros profundos en poco tiempo. El diseño del martillo perforador tiene 4350 BPM, 1050 RPM y su potente mecanismo, que se puede hacer agujeros incluso en los materiales duros. *OJOS: El mandril SDS solo se usa en taladro eléctrico.*',
        '[Cambio Rápido]: La portabroca no se necesita llave, por eso, sea más conveniente cambiar los accesarios, ahorrando tiempo y mejorando la eficiencia del trabajo. El portabrocas SDS-Plus se puede reemplazar por otras portabrocas, que tiene una precisión más alta. El SDS-puls guía la broca para posicionarla precisamente, evita agitación de la broca o la desviación de la posición de perforación y completa la tarea de perforación con mayor facilidad.',
        '[Cuatro Funciones en1]: El interruptor de botón se puede cambiar fácilmente las funciones. La máquina puede cambiarse fácilmente entre las funciones de solo perforación, perforación con percusión y solo percusión. Además, se controla la dirección de cincel plano. El mandril SDS solo se usa en taladro eléctrico.',
        '[Menos Fatiga]: Debido a la absorción de impactos (VDT) y la superficie de agarre suave del mango, el trabajo sería cómodo. El embrague integrado se reduce la reacción y la vibración cuando la broca está atascada para la seguridad en trabajos. Además, su peso relativamente ligero, la máquina podría controlarse bien.',
        '[Accesorios Abundantes]: 1 x Martillo percutor, 3 x Brocas (8, 10, 12 mm), 1 x Cincel Plano (14 x 250 mm), 1 x Cincel de Punta (14 x 250 mm), 1 x Portabrocas 13 mm, 2 x Cepillos de Carbón, 1 x 360 ° Mango Giratorio, 1 x Medidor de Profundidad, 1 x Llave de Broca, 1 x Tubo de Aceite, 1 x Cubierta Antipolvo, 1 x Caja de Almacenamiento, 1 x Instrucciones de Funcionamiento',
      ],
    },
    {
      name: 'Makita HP457DWE - Taladro Percutor A Bateria 18V Litio-Ion 1.5 Ah [Clase de eficiencia energética A]',
      category: 'Taladro Percutor',
      slug: 'Makita-HP457DWE-Taladro-Percutor',
      link: 'https://www.amazon.es/Makita-HP457DWE-Taladro-Percutor-Litio-Ion/dp/B00GDFU56A?_encoding=UTF8&psc=1&refRID=D4KSTNHTV7FYJY985F44&linkCode=ll1&tag=sarria93-21&linkId=c98bbd4522dbaa44a604ee793b1bdf69&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/taladrosPercutor/61-h3jRAYEL._AC_SL1024_.jpg',
      price: 150.51,
      brand: 'Makita',
      rating: 4.6,
      numReviews: 1483,
      countInStock: 45,
      description: [
        'Tiempo de carga 60 minutos aproximadamente con cargador DC18WA',
        'Engranajes metálicos para una perfecta transmisión de la fuerza y mayor durabilidad',
        'Diseño ergonómico con mango antideslizante para un perfecto control de la herramienta y mayor comodidad.',
        '16 posiciones de par de apriete + 1 directa',
        'Porta, brocas autoblocante para un sencillo cambio de la herramienta con sólo una mano',
      ],
    },
    {
      name: 'BLACK+DECKER BCK24D2S-QW - Taladro Percutor 18V (21.000 ipm) y amoladora 125 mm 18V, con 2 baterías litio 2Ah y bolsa de transporte',
      category: 'Taladro Percutor',
      slug: 'BLACK+DECKER-BCK24D2S-QW-Taladro-Percutor',
      link: 'https://www.amazon.es/BLACK-DECKER-BCK24D2S-QW-amoladora-transporte/dp/B07NFLGYHM?_encoding=UTF8&refRID=D4KSTNHTV7FYJY985F44&th=1&linkCode=ll1&tag=sarria93-21&linkId=7fbf85ae0f5347e54a3bdeee3bef8818&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/taladrosPercutor/717-873XtCL._AC_SL1500_.jpg',
      price: 149.99,
      brand: 'Black+Decker',
      rating: 4.2,
      numReviews: 2565,
      countInStock: 2,
      description: [
        'Taladro percutor 18v a batería litio con porta brocas de 10 mm y 10 + 1 posiciones de apriete',
        'Acción percutora de 21.000 ipm (impactos por minuto) ideal para aplicaciones en mampostería y hormigón',
        'Radial de 125 mm a batería con 8.600 rpm de velocidad adecuada para tareas de corte de azulejos, metales, plásticos o para eliminar óxido y pintura',
        'Amoladora con caja de engranajes de aluminio fundido para una óptima disipación del calor y mayor durabilidad',
        'El kit incluye: 2 baterías litio 18v de 2ah, cargador y bolsa de transporte',
      ],
    },

    {
      name: 'Destornillador Eléctrico 6N.m, HYCHIKA Atornillador Eléctrico Inalámbrico 3.6v Batería 2000mAh (Máximo Par 6 N.m) LED Luz, Mandril Magnético, Cargador con Cable 3.5mm, 20 Accesorios',
      category: 'Taladros Atornilladores',
      slug: 'Destornillador-Eléctrico-6Nm',
      link: 'https://www.amazon.es/Destornillador-HYCHIKA-Atornillador-Inal%C3%A1mbrico-Accesorios/dp/B086SQK2RK?_encoding=UTF8&psc=1&refRID=JZ7WZC0127YKQZ9D6798&linkCode=ll1&tag=sarria93-21&linkId=8c28bf90553ea943cc355077905fe972&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/taladrosAtornillador/81Kr8gxqcsL._AC_SL1500_.jpg',
      price: 24.99,
      brand: 'HYCHIKA BETTER TOOLS FOR BETTER LIFE',
      rating: 4.3,
      numReviews: 7657,
      countInStock: 0,
      description: [
        '【Batería de 2000 mAh y carga protección】Nuestro destornillador eléctrico tiene una batería grande de 2000 mAh, que tiene un mayor tiempo de uso que otros productos. Nuestro destornillador eléctrico siempre ejecute a plena potencia y par completo, no habrá una disminución en el par y la potencia debido a la batería baja. El cargador proteger la batería de litio mediante trickle charging, lo que efectivamente extiende la vida útil de la batería de litio(3 años)',
        '【Destornillador eléctrico con 6 N.m Máximo Par y mandril magnético】Operación continua a plena potencia y par completo (puede atornillar 340 tornillos después de cada carga completa), utilizando más ahorro de mano de obra. Adecuados para ensamblar y reparar muebles, aptar para uso DIY, doméstico y de oficina. El portabrocas magnético puede ser más conveniente y el reemplazo rápido de diferentes tipos de accesorios (No necesita apriete de rotación, simplemente conecte o desconecte directamente)',
        '【Atornillador eléctrico con el motor último modelo 2020, 2 formas de usar y 1 LED luz】Los motores más recientes tienen menor consumo de energía, menor generación de calor y mayor vida útil (más de 3 años). Cuando se usa en un espacio pequeño, puede cambiar la forma girando el asa para obtener una experiencia más conveniente. Puede elegir apretar o aflojar con los botones de bloqueo izquierdo y derecho. Tiene luces LED en los extremos delantero, proporciona efectos de iluminación muy claros',
        '【Atornillador eléctrico con 20 Accesorios 】20 accesorios satisfacen la mayoría de sus necesidades, puede consultar nuestra tabla de accesorios para obtener modelos de accesorios detallados. Le recomendamos mucho que utilice el cargador incluido en nuestro paquete, que tiene protección de carga y reduzca el daño a la batería de litio durante cada carga y asegúrese de que la cantidad de carga y descarga cíclica de la batería de litio sea más de 625 veces',
        '【El paquete】No incluye el maletín. 1 x HYCHIKA Destornillador eléctrico 3.6V; 20 x accesorios(Debajo del compartimento dentro de la caja de cartón); 1 x cargador; 1 x manual de usuario en español. (1/4 de pulgada (6,35 mm) con portabrocas magnético, cargar completa en solo 4 horas ( modo de carga protección). Somos fabricante directo de HYCHIKA, por eso, usted no se preocupe nada, cualquer problema contacto con nos directamente, le ayudaremos a resolverlo (7 x 24horas)',
      ],
    },
    {
      name: 'Taladro Atornillador 12V con 2 Baterías, HYCHIKA Destornillador Eléctrico, 30N.m Par Máx, 1.5 Ah Batería, 1 Hora de Carga Rápida, 6PCS Puntas y HSS Brocas, 5PCS Llaves de vaso, 4PCS Brocas de Madera',
      category: 'Taladros Atornilladores',
      slug: 'Taladro-Atornillador-12V-HYCHIKA',
      link: 'https://www.amazon.es/Atornillador-Bater%C3%ADas-HYCHIKA-Destornillador-El%C3%A9ctrico/dp/B082HTSRYV?_encoding=UTF8&psc=1&refRID=JZ7WZC0127YKQZ9D6798&linkCode=ll1&tag=sarria93-21&linkId=ecd675e84027b6f9b34c94aa5244b74f&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/taladrosAtornillador/81NUfvNm4wL._AC_SL1500_.jpg',
      price: 54.99,
      brand: 'HYCHIKA BETTER TOOLS FOR BETTER LIFE',
      rating: 4.4,
      numReviews: 4216,
      countInStock: 0,
      description: [
        '23 ACCESORIOS RICOS Y DOS BATERIAS DE LITIO - 23 accesorios ricos se satisfecha a la mayoría necesidad de trabajo.Dos baterías de litio pueden mejorar enormemente la eficiencia y el tiempo de trabajo.Adecuado para taladrar agujeros en metal, madera y plástico; tornillos de fijación y aflojamiento.',
        '21+1 AJUSTES DE TORQUE - 21+ 1 par motor sin cable y 12V/1500 mAh Mandril de cierre de 10mm (3/8 ") Aplicable a la perforación del azulejo de piso y metal y la madera, también retiro de los tornillos es esfuerzo y práctico',
        '2 MARCHA DE VELOCIDAD - Ajuste de 2 velocidades e interruptor positivo y negativo. Se pueden seleccionar diferentes velocidades de salida según diferentes escenarios de uso. Con 2 velocidades variables (0-400 rpm y 0-1500 rpm) para la amplia aplicaciones de perforación, atornillado y percusión.',
        'DISEÑO ERGONÓMICO - Cuenta con una luz LED integrada para una iluminación óptima de las áreas de trabajo con oscuridad, el indicador muestra la capacidad de la carga de la batería, fácil de transportar con un clip resistente para el cinturón.',
        'CONTENIDO DEL PAQUETE - 1×HYCHIKA Taladro Atornillador 12V, 2×baterías, 5×Llaves de vaso, 6×Puntas, 6×HSS Brocas, 4×Brocas de Madera, 1×Adaptador, 1×Bolsa de Accesorio, 1×Bolsa de Herramienta.',
      ],
    },
    {
      name: 'Taladro Atornillador 2 Baterías, GOXAWEE 100Pcs Kit Taladro Bateria/Destornillador Eléctrico (2 Baterías de Litio 1500mAh, 30N.m Par Máx, 2 Velocidades, 10mm Portabrocas Automático)',
      category: 'Taladros Atornilladores',
      slug: 'Taladro-Atornillador-2-Baterías-GOXAWEE-100Pcs',
      link: 'https://www.amazon.es/Atornillador-GOXAWEE-Destornillador-Velocidades-Portabrocas/dp/B08L7RBTW8?_encoding=UTF8&psc=1&refRID=JZ7WZC0127YKQZ9D6798&linkCode=ll1&tag=sarria93-21&linkId=94f50e1a89f979e14962352ea60a63a3&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/taladrosAtornillador/71iF7VUX5aL._AC_SL1500_.jpg',
      price: 45.98,
      brand: 'GOXAWEE',
      rating: 4.3,
      numReviews: 220,
      countInStock: 0,
      description: [
        '【 x2 Baterías y carga rápida 】El taladro incluye 2 baterías de iones de litio de 1500 mAh, lo que permite un uso sin restricciones, la batería se carga completamente en tan solo 1 hora.',
        '【 2 Velocidades Taladro Inalámbrico 】Atornillador inalámbrico equipado con ajuste de 2 velocidades a 0-350/ 1350 rpm. El disparador de presión de velocidad variable le permite controlar la velocidad de perforación ● Baja velocidad (0-350 rpm) es ideal para atornillar ● Alta velocidad (0-1350 rpm) es más eficiente para las tareas de perforación.',
        '【 18-30Nm & 15+1 Ajuste de Par 】El destornillador eléctrico le ofrece más de 15 opciones de ajustes precisos para la mayoría de las necesidades diarias; ☛ Gira el círculo del cabezal de perforación para cambiar la velocidad, el par máximo a 30 Nm es ideal para trabajos mas complejos. ▲Perforación máxima: 10 mm (metal) & 15 mm (madera) / Atornillado máximo: 10mm.',
        '【 Diseño Ergonomico & Personalidad 】✔ El taladro atornillador eléctrico proporciona al usuario un cómodo, suave y equilibrado agarre. ✔ La luz LED ayuda a perforar y atornillar en lugares oscuros ✔ El interruptor giratorio le permite rotar hacia adelante o hacia atrás según sus necesidades ✔ Bloqueo automático del portabrocas de 0,8-10mm para brocas de cambio rápido.',
        '【 Ideas regalo y agradable regalo 】x1 GOXAWEE Taladro Atornillador, x2 Batería recargable, x1 Cargador rápido, x1 Eje flexible (250mm), x9 Llaves de tubo, x6 Puntas de destornillador, x1 Adaptador hexagonal, x1 Soporte de extensión hexagonal, x3 Brocas para madera, x3 Brocas para metal, x1 Broca de carburo, x72 Accesorios de fijación y x1 Caja de herramientas.',
      ],
    },
    {
      name: 'Taladro Atornillador 21V, TEENO 41Pcs Kit Destornillador Eléctrico (2 Baterías de Litio 1500mAh, 40N.m Par Máx, 2 Velocidades, 10mm Portabrocas Automatico)',
      category: 'Taladros Atornilladores',
      slug: 'Taladro-Atornillador-21V-TEENO',
      link: 'https://www.amazon.es/TEENO-taladro-bater%C3%ADas-accesorios-profesionales/dp/B075FPNWM2?_encoding=UTF8&psc=1&refRID=JZ7WZC0127YKQZ9D6798&linkCode=ll1&tag=sarria93-21&linkId=725362d1617b0d1ae9cabd9c44db7e9e&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/taladrosAtornillador/61cfqqH5u7S._AC_SL1000_.jpg',
      price: 61.99,
      brand: '	TEENO',
      rating: 4.1,
      numReviews: 1258,
      countInStock: 0,
      description: [
        'Taladro sin cuerda Componente del paquete: 1 * taladro sin cable + 1 * Caso plástico + 1 * Guantes profesionales + + 35 * Accesorios + 1 * Universal Head + 1 * Cargador + 2 * Baterías',
        'Tipo de fuente de alimentación: Batería',
        'Batería: 2 baterías de iones de litio 21V',
        'Tipo del tirador: 10m m Automático',
      ],
    },
    {
      name: 'BLACK+DECKER BCF611CK-QW - Atornillador a batería 3.6V(1.5Ah) litio, 5.5Nm, de carga rápida',
      category: 'Taladros Atornilladores',
      slug: 'BLACK+DECKER-BCF611CK-QW -Atornillador',
      link: 'https://www.amazon.es/BLACK-DECKER-BCF611CK-QW-Atornillador-bater%C3%ADa/dp/B07TFHGZXF?_encoding=UTF8&psc=1&refRID=JZ7WZC0127YKQZ9D6798&linkCode=ll1&tag=sarria93-21&linkId=8f64e0c1b5ce5726ed532f2321b17a3c&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/taladrosAtornillador/71ITLPRvwyL._AC_SL1500_.jpg',
      price: 24.49,
      brand: 'Black+Decker',
      rating: 4.4,
      numReviews: 1485,
      countInStock: 19,
      description: [
        ' Atornillador con batería de litio integrada de 3.6v(1.5ah) y de carga rápida en menos de 1 hora con puerto de carga micro usb.',
        ' Par de apriete de 5.5nm, velocidad de 180 rpm y porta-puntas de 1/4” hexagonal que permite un cambio fácil y rápido de los accesorios.',
        ' Probado: 100 tornillos con una carga de 15 minutos y hasta 500 tornillos con una carga de 60 minutos (resultados obtenidos con tornillos 3.5 x 25mm en madera de pino de 408mm con agujero guía pre-establecido).',
        ' Función reversible, modo linterna y diseño ultra compacto que ofrecen comodidad y eficiencia mientras esta funcionando.',
        ' Incluye: 10 puntas para atornillar, cargador rápido de 2ah y estuche de almacenamiento.',
      ],
    },

    {
      name: 'Black+Decker BEG010-QS - Amoladora 115mm, 710W, 12.000 rpm',
      category: 'Amoladoras',
      slug: 'Black+Decker-BEG010-QS-Amoladora',
      link: 'https://www.amazon.es/BLACK-DECKER-BEG010-QS-Amoladora-12-000/dp/B07N17F4BL?_encoding=UTF8&refRID=TA4Z8TTZ9RF8AJWMX8CG&th=1&linkCode=ll1&tag=sarria93-21&linkId=1b30c2a015bdedde3d1f8b8c234858cd&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/amoladoras/81M6s7FW1uL._AC_SL1500_.jpg',
      price: 24.93,
      brand: 'Black+Decker',
      rating: 4.5,
      numReviews: 2408,
      countInStock: 36,
      description: [
        'Radial de 115 mm con potente motor de 710w',
        'Facilita el corte de tubos metálicos, losas de piedra y baldosas de cerámica, así como la eliminación de óxido y pintura',
        'Motor de 12.000 rpm con protección contra re-arranque para mayor seguridad mientras opera',
        'Mango ajustable en dos posiciones para mayor versatilidad mientras trabajas',
        'El diámetro compacto de esta amoladora con cable permite un agarre cómodo y le permite acceder a áreas difíciles',
      ],
    },
    {
      name: 'Bosch Professional GWS 7-115 E - Amoladora angular (720 W, 2800 – 11000 rpm, Ø Disco 115 mm, protección rearranque, en caja)',
      category: 'Amoladoras',
      slug: 'Bosch-Professional-GWS-7-115-E-Amoladora-angular',
      link: 'https://www.amazon.es/Bosch-GWS-7-115-Professional-Miniamoladora/dp/B018YPAI9A?_encoding=UTF8&refRID=TA4Z8TTZ9RF8AJWMX8CG&th=1&linkCode=ll1&tag=sarria93-21&linkId=568aacd357007c7d2b68d25ef269b2ab&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/amoladoras/81HD9lo7FrL._AC_SL1500_.jpg',
      price: 79.0,
      brand: 'Bosch',
      rating: 4.7,
      numReviews: 13261,
      countInStock: 7,
      description: [
        'Incluye miniamoladora gws 7-115 e, cubierta protectora, brida de fijación, empuñadura adicional, llave de dos agujeros, tuerca tensora',
        'Perímetro de empuñadura reducido con 720 w de potencía',
        'Perímetro de empuñadura reducido (176 mm), comparado con otras amoladoras angulares de la misma categoría de potencía, que proporciona una gran comodidad en el trabajo',
        'Motor de 720 w de potencía con un peso de solo 1, 9 kg, para trabajar durante periodos prolongados',
        'Cabezal plano para que el trabajo resulte cómodo incluso en zonas estrechas',
        'Protección contra rearranque evita la puesta en marcha automática de la herramienta tras una interrupción de corriente',
        'Preselección del número de revoluciones en 6 niveles para trabajar con diferentes materiales',
      ],
    },
    {
      name: 'Einhell Amoladora angular TC-AG 125 (850W, 12.000 1/min de velocidad, disco de 125mm-ø, protector de disco, bloqueo de husillo, cabezal de engranaje plano de aluminio)',
      category: 'Amoladoras',
      slug: 'Einhell-4430619-TC-AG-125-Amoladora-Angular',
      link: 'https://www.amazon.es/Einhell-4430619-125-di%C3%A1metro-850/dp/B00TFZFVL4?_encoding=UTF8&refRID=TA4Z8TTZ9RF8AJWMX8CG&th=1&linkCode=ll1&tag=sarria93-21&linkId=78b7bf0ce3fe53441fa795c0a56ded98&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/amoladoras/51lNAaPVRIL._AC_SL1464_.jpg',
      price: 34.0,
      brand: 'Einhell',
      rating: 4.4,
      numReviews: 2119,
      countInStock: 11,
      description: [
        'Carcasa de plástico ergonómica con robusto cabezal de engranaje plano de aluminio',
        'Gran potencia de 850 W con velocidad de giro constante de 12.000 revoluciones por minuto',
        'Asidero adicional montable en 2 posiciones para cada tarea',
        'Práctico bloqueo de husillo para el cambio de herramienta rápido',
        'Incluida llave de gancho para el cómodo cambio de herramienta',
        'Suministro de red de 230 V | 50 HZ',
        'Peso bruto del producto sin embalaje de 2,3 Kg',
      ],
    },
    {
      name: 'Amoladora Angular Profesional,Tilswall 860W 12000 RPM 125mm,Amoladora Angular con 3 Discos de Corte y 2 Esmerilado,Cubierta Protectora para Esmerilado/Pulido/Corte',
      category: 'Amoladoras',
      slug: 'Amoladora-Angular-Profesional-Tilswall',
      link: 'https://www.amazon.es/Amoladora-Profesional-Tilswall-Esmerilado-Protectora/dp/B07VQ5MPZL?_encoding=UTF8&psc=1&refRID=TA4Z8TTZ9RF8AJWMX8CG&linkCode=ll1&tag=sarria93-21&linkId=4a2390399e542069107edd08b32035ac&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/amoladoras/81OvGYvmurL._AC_SL1500_.jpg',
      price: 35.99,
      brand: 'Tilswall',
      rating: 4.4,
      numReviews: 951,
      countInStock: 0,
      description: [
        '【860W Potente】:Amoladora angular Tilswall con un motor de alto rendimiento de 860W y una velocidad de hasta 12,000 rpm que proporciona un procesamiento eficiente para aplicaciones profesionales de corte y rectificado',
        '【Diseño De Seguridad】:El diseño compacto y el bajo peso de 1.5 kg es fácil y cómodo a mano.El mango lateral de dos posiciones tiene forma de barril con 2 cubiertas protectoras para reducir la vibración y proporcionar un mejor control durante la operación,no se preocupe por usar la seguridad.Además,con un innovador diseño de ventilación ayuda a evitar el polvo y la suciedad para un mejor rendimiento',
        '【2 Cubiertas Protectores Y 5 Discos】:Hay 2 cubiertas protectoras que se adaptan a cualquier necesidad (rectificado o corte) y con la ayuda de una llave que le ofrecemos,puede cambiar los discos de forma rápida y fácil.Además,hay 5 discos (2 para rectificar y 3 para cortar) para sus diferentes necesidades',
        '【Dispositivo Esencial IND】:Es un producto ideal para bricolaje,rectificado de metal,corte de barras,mosaico y estuco,enrutamiento de mortero,pulido,lijado del aficionado en casa y rectificado,corte,cepillo y arena de metal',
        '【Paquete Incluido】: 1 x amoladora angular Tilswall,3 x discos de corte,2 x discos de molienda,2 x cubierta protectora,1 x llave,1 x cepillo de carbón y 1 x manual de usuario francés en uno kraft box.Si tiene algún problema en 28 meses,contáctenos,no se preocupe,siempre estamos a su servicio',
      ],
    },
    {
      name: 'Amoladora Angular 18V, HYCHIKA Radial Angular Inalámbrico, 8500RPM con 4.0Ah Batería, 4*Discos para Lijar y 1*para Cortar, Mango Ajustable, Cargador Rápido, Amoladora Angular a Batería para Multiusar',
      category: 'Amoladoras',
      slug: 'Amoladora-Angular-18V-HYCHIKA',
      link: 'https://www.amazon.es/HYCHIKA-BETTER-TOOLS-FOR-LIFE/dp/B08DJ4NWHS?_encoding=UTF8&psc=1&refRID=TA4Z8TTZ9RF8AJWMX8CG&linkCode=ll1&tag=sarria93-21&linkId=1495d2d2148aaf57a6a957123c6ae2fe&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/amoladoras/81ByBSsvBOL._AC_SL1500_.jpg',
      price: 89.99,
      brand: '‎HYCHIKA BETTER TOOLS FOR BETTER LIFE',
      rating: 4.4,
      numReviews: 174,
      countInStock: 0,
      description: [
        '✔️MULTIUSOS & 4.0AhBATERÍA✔️ Amoladora Angular utilizado para cortar, y pulido de diversos materiales, el procesamiento de esmerilado, incluidos materiales sólidos como metal, porcelana, hormigón, tuberías, conductos, etc. Vienido con 4,0AhBatería y 1HCargador rápido, proporcionado una mayor potencia para satisfacer sus necesidades laborales.',
        '✔️PROTECCIÓN SEGURA✔️ Amoladora Angular a batería tiene función de protección integrada contra sobrecarga y sobrecalentamiento es para proteger la batería. Caperuza protectira ofrece protección adicional en la molienda, corte evitando que las chispas salpican.',
        '✔️MANGO AJUSTABLE✔️ El mango auxiliar del Radial Angular Inalámbrico cubre goma blanda, se siente más cómodo de usar y operación es más conveniente. El mango a prueba de golpes de 3 posiciones proporciona una antivibración mejorando una comodidad y un control del operador.',
        '✔️5* DISCOS 115MM✔️ 4*Disco abrasivo para Lijar y 1* para cortar; Se utiliza para pulir piezas metálicas, juntas de soldadura, eliminar golpes y óxido y desbarbar metales, también para cobre, aluminio, diversos metales, materiales y madera. (Diámetro de la rueda de Radial Angular es de 115 mm. )',
        '✔️EL PAQUETE✔️ 1* HYCHIKA Amoladora Angular a batería 18V, 2* Disco abrasivo (60/120 Grano), 2* Discos para Lijar, 1* Disco para Cortar, 1* Caperuza Protectora, 1*Mango Auxiliar, 1* 4,0Ah Batería 18V, 1HCargador Rápido. ☎☎☎ Cuando encuentre algún problema, comuníquese con nuestro personal de postventa a tiempo.',
      ],
    },

    {
      name: 'BLACK+DECKER Lijadora de Detalle Mouse 55W 11.000RPM Diametro Orbita 1.5mm Incluye 15 Accesorios y Bolsa de Transporte BEW230BC-QS',
      category: 'Lijadoras',
      slug: 'BLACK+DECKER-Lijadora-de-Detalle-Mouse',
      link: 'https://www.amazon.es/BEW230BC-QS-Lijadora-di%C3%A1metro-Accesorios-Transporte/dp/B07MKNMDD4?_encoding=UTF8&refRID=NSBTMPGBAZ5NXZB52ZWR&th=1&linkCode=ll1&tag=sarria93-21&linkId=43ec299f17f1a79f2707558c4f052909&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/lijadoras/71rSLwgwSgL._AC_SL1500_.jpg',
      price: 36.39,
      brand: 'Black+Decker',
      rating: 4.5,
      numReviews: 3708,
      countInStock: 31,
      description: [
        'Lijadora orbital de detalles 55W adecuada para pintar, barnizar, eliminar óxido y lijar en espacios reducidos',
        'Diámetro de órbita 1.5mm y tamaño de hoja 110mm/cm2',
        'Velocidad de 11.000 rpm entrega un rendimiento óptimo para aplicaciones de detalle',
        'Cuenta con adaptador de aspirador para mantener el área de trabajo limpia',
        'Incluye: 15 accesorios lijar y bolsa de transporte',
      ],
    },
    {
      name: 'Bosch PSM 100 A - Multilijadora, 3 hojas de lija K 80/ K 120/ K 160, maletín (100 W, nº de carreras en vacío: 26.000 opm, Ø circuito oscilante: 1,4 mm)',
      category: 'Lijadoras',
      slug: 'Bosch-PSM-100-A-Multilijadora',
      link: 'https://www.amazon.es/Bosch-Multilijadora-hojas-malet%C3%ADn-carreras/dp/B00IPIYLO0?_encoding=UTF8&psc=1&refRID=NSBTMPGBAZ5NXZB52ZWR&linkCode=ll1&tag=sarria93-21&linkId=65f27e01389253c62a4024520bf89d57&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/lijadoras/81r-zQLJMOL._AC_SL1500_.jpg',
      price: 68.93,
      brand: 'Bosch Home and Garden',
      rating: 4.6,
      numReviews: 1313,
      countInStock: 4,
      description: [
        'Incluye: Multilijadora PSM 100 A, 3 hojas de lija K 80/ K 120/ K 160, maletín',
        'PSM 100 A: la lijadora multitalento de fácil manejo',
        'Ligera y compacta, perfecta para lijar en zonas de difícil acceso, así como en superficies pequeñas y medianas',
        'Trabajo limpio gracias al sistema microfiltro: el elemento de aspiración integrado aspira el polvo directamente al interior del depósito del sistema microfiltro suministrado',
        'Cierre de cardillo para el cambio rápido de la hoja de lija',
        'Placa lijadora dividida en dos: para el aprovechamiento óptimo de la hoja de lija, la punta delta de la hoja y de la placa pueden soltarse y girarse sin esfuerzos',
        'Conexión para aspiración de polvo para aspiradores universales',
      ],
    },
    {
      name: 'Lijadora Eléctrica 200W Tilswall, 15000RPM Lijadora de Detalles Mouse de Diámetro Orbital 1,6mm, con 12 Piezas Lijas de 60 grano y de 120 grano para Alisar Madera y Quitar Pintura',
      category: 'Lijadoras',
      slug: 'Lijadora-Eléctrica-200W-Tilswall',
      link: 'https://www.amazon.es/Lijadora-El%C3%A9ctrica-Tilswall-Detalles-15000RPM/dp/B07X8ZR5WD?_encoding=UTF8&psc=1&refRID=NSBTMPGBAZ5NXZB52ZWR&linkCode=ll1&tag=sarria93-21&linkId=a935cb4f629525e24d0ee280474df994&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/lijadoras/71xGEsZulBL._AC_SL1500_.jpg',
      price: 34.99,
      brand: 'TILSWALL',
      rating: 4.2,
      numReviews: 1478,
      countInStock: 0,
      description: [
        '【Alto Rendimiento】: Nuestra lijadora de acabado tiene un motor de cobre fino de 200 W con baja resistencia, que ofrece un rendimiento de 15000 RPM. La órbita excéntrica más alta (diámetro de 1,6 mm) es más uniforme e ideal para lijar, pulir las superficies pequeñas y reparar pintura',
        '【Caja de Polvo】: Nuestra lijadora es diseñada con una gran caja reutilizable para recoger el polvo, proporcionándole un entorno de trabajo limpio. El diseño compacto se fija de forma segura en la máquina para evitar que la caja se caiga durante el uso, brindando más conveniencia para usted.',
        '【Interruptor de Polvo & Enfriamiento】: El interruptor a prueba de polvo evita que las virutas de madera entran en la máquina de lijar madera, mantenióndolo limpio y extendiendo su vida útil. Además, la lijadora está equipado con una fuerte disipación de calor, permite que la máquina funcione eficientemente sin quemar y dañar',
        '【Uso Cómodo】: La lijadora de detalles de 1.15 kg es ligero, su mango de goma suave puede reducir efectivamente las vibraciones durante el uso. Además, el diseño ovalado brinda a su mano un mejor agarre y control, evitando la fatiga. Muy adecuado para pulir madera, pintura y muebles, etc.',
        '【Paquete Incluido】: Nuestro paquete se viene con 1 x lijadora para madera Tilswall, 12 x lijas abrasivas (6 piezas x 80 grano abrasivo,6 piezas x 120 granos abrasivos), 1 x Manual en español. Si tiene algún problema en 28 meses, contáctenos. No se preocupe, estamos siempre a su servicio',
      ],
    },
    {
      name: 'Lijadora Orbital 300W, HYCHIKA Lijadora Eléctrica con Motor de Cobre Puro, 6 Velocidad, 13000RPM, 12PCS Lija de 125mm (240/120/80 Grano), con Bolsillo Lavable de Recogida, para Lijar Madera y Metal',
      category: 'Lijadoras',
      slug: 'Lijadora-Orbital-300W-HYCHIKA',
      link: 'https://www.amazon.es/Lijadora-HYCHIKA-Velocidad-Ajustable-El%C3%A9ctrica/dp/B08DHP1D2X?_encoding=UTF8&psc=1&refRID=NSBTMPGBAZ5NXZB52ZWR&linkCode=ll1&tag=sarria93-21&linkId=5fe374b9d5bb54a83212d7ee1c48191d&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/lijadoras/81hz0B-fX9S._AC_SL1500_.jpg',
      price: 36.99,
      brand: 'HYCHIKA BETTER TOOLS FOR BETTER LIFE',
      rating: 4.3,
      numReviews: 260,
      countInStock: 0,
      description: [
        '【6 VELOCIDADES】 Lijadora Orbital con motor de cobre puro, tiene un botón para ajustar 6 velocidad ajustable. Esto le permite elegir la velocidad de Lijadora Orbital Electrica más adecuada para el trabajo. Velocidad entre 6000 y 13000RPM, Potencia: 300W, puede mejorar la eficiencia. Lijas gruesas se giran a alta velocidad para un pulido áspero y el finas para un pulido fino.',
        '【12PCS Lijas】 Lijadora Orbital está equipada con 12 Lijas de Lijadora de malla de 80, 120, 240 granos, que pueden usarlos para pulir materiales de madera y metal. Diámetro de lijadora es 125mm, Es fácil de encontrar y comprar lijas en Amazon.',
        '【BASE GIRATORIA 360 °】 Base de lijado giratoria de 360 ° asegura que la superficie de lijado queda lisa sin trazas. Cambia rápidamente las lijas para mejorar en gran medido la eficiencia del trabajo.',
        '【RECOGIDA DE POLVO】 Lijadora Electrica está diseñada con 8 orificios de recolección de polvo, combinado con un sistema de recolección de polvo y una caja de recolección. La eficiencia es mayor, lo que puede trabajar en un ambiente más limpio y cómodo. Es muy fácil de instalar esta caja y quitarla. Se puede limpiarla con agua. Hay un anillo de goma en la boca de la bolsa de la aspiradora, que hace que esté bien conectada, y las astillas no se dispersan fácilmente.',
        '【TRABAJO EFICIENTE Y CÓMODO】 Está cubierta con goma, y tiene varias formas de agarre. Es muy fácil de operar esta Lijadora Orbital Electrica con una sola mano y mejora la comodidad y el control del operador.',
      ],
    },
    {
      name: 'Lijadora Eléctrica, TECCPO Máquina Lijadora Compacta para Madera, 15500 RPM con Recolección de Polvo Reutilizable, 12 Piezas de Papel de Lija Incluidos - TAMS23P',
      category: 'Lijadoras',
      slug: 'Lijadora-Eléctrica-TECCPO-Máquina-Lijadora',
      link: 'https://www.amazon.es/El%C3%A9ctrica-TECCPO-Professional-Contenedor-Reutilizable/dp/B07VPQLZ6T?_encoding=UTF8&psc=1&refRID=NSBTMPGBAZ5NXZB52ZWR&linkCode=ll1&tag=sarria93-21&linkId=b449e2db79349481bbf8f636b1e2ba23&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/lijadoras/71uclaE+mLL._AC_SL1500_.jpg',
      price: 30.59,
      brand: 'TECCPO',
      rating: 4.2,
      numReviews: 189,
      countInStock: 0,
      description: [
        '【Motor de 15,500 RPM】 El motor de cobre puro con velocidad 15500 revoluciones por minuto, se puede usar de manera más agresiva para sacar más material de la superficie más rápido y también se puede usar en materiales más duros de manera más efectiva. Ahorrará tiempo en un momento y reducirá la fatiga del usuario. Las palas del motor están fundidas en aleación de aluminio.',
        '【Eficiente】La alta órbita excéntrica (1,5 mm de diámetro) crea un área de lijado más uniforme y grande, lo que permite, el tiempo de trabajo en comparación con otras lijadoras de baja potencia, indica una mejor calidad y experiencia',
        '【Eliminación de polvo】La acumulación prolongada de polvo dañará el motor. Por lo tanto, hemos diseñado un interruptor a prueba de polvo para mantener las partículas fueras, lo que extenderá significativamente la vida de la lijadora. La caja de polvo de ABS es reciclable al descargar fácilmente el polvo, facilita las operaciones de limpieza. Después de cada uso, simplemente desenchufe el contenedor de recolección y deseche el contenido.',
        '【Cómodo】 Diseño ergonómico del mango de la palma con goma optimizada para un mayor control y un agarre cómodo. También para la máxima comodidad y flexibilidad. Compacto y liviano, es fácil de transportar y trabajar en espacios reducidos.',
        '【2 Años Garantía de Calidad】 El pulido de vidrio, azulejos, madera, metal y otros materiales se pueden obtener pegando diferentes tipos de papel de lija. TECCPO ofrece una garantía de satisfacción de 2 años. Si tiene alguna pregunta.',
      ],
    },

    {
      name: 'E·Durable Soldadores de Estaño Electronica, 60W 220V Kit del Soldador 5pcs Puntas Diferentes,Alambre de Soldadura Soporte,Cortador,Pinzas,destornillador',
      category: 'Soldadores',
      slug: 'E·Durable-Soldadores-de-Estaño-Electronica-60W-220V',
      link: 'https://www.amazon.es/%C2%B7Durable-Soldador-electrico-Destornilladores-Soldadura/dp/B07MW64Z9H?_encoding=UTF8&refRID=QJGZR3QF2MEDPG5TDGNC&th=1&linkCode=ll1&tag=sarria93-21&linkId=0fa13090428ae9c59d045b6597d670bb&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/soldadores/61sONbaNn2L._AC_SL1000_.jpg',
      price: 13.99,
      brand: 'E·Durable',
      rating: 4.3,
      numReviews: 452,
      countInStock: 0,
      description: [
        ' Kits de soldadura ampliamente utilizados: las herramientas de soldadura de soldador se usan ampliamente para soldar placas de circuito, reparación de electrodomésticos, aficionados al bricolaje en el hogar, soldadura de joyas. La mejor opción para principiantes en soldadura',
        ' Excelente pistola de soldadura: no necesita estación de soldadura, solo conéctelo y juegue. Fácil de operar Ajuste la temperatura de acuerdo a sus necesidades con la rueda de perilla del soldador electrónico.',
        ' 5 puntas de hierro: cinco puntas diferentes hacen que el soldador sea fácil de colocar para guitarra, computadoras, hardware y condensadores o accesorios de TV, etc.',
        ' Más Accesorios：este destornillador mini pluma incluye 2 brocas de destornillador de dos puntas que funciona muy bien para el iPhone 7/7Plus, iPhoneX, iPhone Plus 8/8, P 6/6/6/5/5 / 5C/4S/4/SE, iPod, iWatch, este kit de reparación de iphone incluyen Y000 triwing destornillador Pentalobe p2 destornillador, ph0000 destornillador phillips y 2,0 mm cabeza plana Destornillador bit set',
        ' Kit de soldadura de hierro Soldering de hierro incluyen: soldador, para bomba, 5pcs diferentes puntas, pinzas, soldadura de tubo, soporte, alambre de corte diagonal, herramientas de palanca de doble cabezal plástico verde es mejor para el uso de vario reparado diyer',
      ],
    },
    {
      name: 'Campingaz 2000026173 - Soldador',
      category: 'Soldadores',
      slug: 'Campingaz-2000026173-Soldador',
      link: 'https://www.amazon.es/Campingaz-2000026173-Soldador/dp/B01AJE8OH2?_encoding=UTF8&psc=1&refRID=QJGZR3QF2MEDPG5TDGNC&linkCode=ll1&tag=sarria93-21&linkId=09bf3607a3174248b93dc9b61fe3eb2d&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/soldadores/71erzy6QM5L._SL1500_.jpg',
      price: 21.36,
      brand: 'CAMPINGAZ',
      rating: 3.4,
      numReviews: 89,
      countInStock: 4,
      description: [
        ' Potencia 1650 W. Consumo 120 g/h. Autonomía: 1h 40 min',
        ' Temperatura 1750ºC. Boquilla de latón.',
        ' Gama de boquillas intercambiables. Ajuste de la llama con una mano',
      ],
    },
    {
      name: 'Dremel Versatip 2000 - Pirograbador a gas butano con 6 puntas para soldadura, pirografo, fusión, corte en caliente, compresión (duración de encendido máximo 90 min)',
      category: 'Soldadores',
      slug: 'Dremel-Versatip-2000-Pirograbador-a-gas-butano',
      link: 'https://www.amazon.es/Dremel-Versatip-2000-6-encendido-accesorios/dp/B000QGC6XW?_encoding=UTF8&refRID=QJGZR3QF2MEDPG5TDGNC&th=1&linkCode=ll1&tag=sarria93-21&linkId=860d72f1c92269e161575a85d678ffee&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/soldadores/61lpNdFHpdL._SL1500_.jpg',
      price: 44.0,
      brand: 'Dremel',
      rating: 4.5,
      numReviews: 8463,
      countInStock: 16,
      description: [
        'Incluye: Versatip, cabezal con soplador de aire caliente, cabezal de llama ancha/plana, caja metálica de almacenaje, cuchilla de corte, cuchilla para corte en caliente, esponja para soldadura, estuche, estaño para soldar, punta de soldadura y reflector',
        'Una herramienta para 6 aplicaciones diferentes: soldadura, fusión, corte en caliente, compresión, grabado a fuego (pirograbado) y eliminación de pintura',
        'Siempre lista para usar',
        'Se puede utilizar en cualquier momento y en cualquier parte',
        'Permite realizar tareas complejas y minuciosas',
      ],
    },
    {
      name: 'Bostar Máquinas de Soldadura de Parachoques Automáticos 220V Herramienta de Reparacion de Parachoques de Coche de Plastico Grapador Caliente Carenado de Guardafango de Carroceria',
      category: 'Soldadores',
      slug: 'Bostar-Máquinas-de-Soldadura-de-Parachoques',
      link: 'https://www.amazon.es/Bostar-Parachoques-Autom%C3%A1ticos-Herramienta-Guardafango/dp/B08GXBJHR5?_encoding=UTF8&psc=1&refRID=QJGZR3QF2MEDPG5TDGNC&linkCode=ll1&tag=sarria93-21&linkId=11d1e7bb5e801d98f1167b37ae565a3c&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/soldadores/91srqH+z+2L._AC_SL1500_.jpg',
      price: 36.99,
      brand: 'Bostar',
      rating: 4.1,
      numReviews: 15,
      countInStock: 0,
      description: [
        '【Juego de reparación práctico】El MANUAL en Español se puede descargar encima de la descripción del producto. Un juego de máquina de soldar con herramientas. Fácil de usar para reparar varios tipos de plásticos.AC 220V con niveles de calentamiento es ideal para soldar rápida y fácilmente piezas de plástico agrietadas y dañadas, volviendo a unir perfectamente.',
        '【Seguro y conveniente】Aprox. 24 cm, pequeño y ligero. Fácil de usar con una mano. Con orificios de enfriamiento y luces indicadoras LED. Un kit de grapadora en caliente extremadamente fácil de usar y extremadamente práctico diseñado para reparar plásticos.',
        '【Ampliamente utilizado】Se puede utilizar para reparar muchos tipos de plástico, como: parachoques, interiores de automóviles, motocicletas, vehículos todo terreno, SUV, embarcaciones,juguetes, lámparas y productos electrónicos.',
        '【Para reparaciones eficientes】Los enchufes estándar de EU con fuente de alimentación de 220V 50W brindan una velocidad de calentamiento rápida. Facilite el progreso de la reparación. La operación es simple, y muchas piezas de plástico se pueden reparar realmente para rescatarlas del basurero.',
        '【El paquete incluye】Contiene 1*máquinas de soldadura de parachoques,1*estuche de transporte,200*clavos para soldar(4 tipos),1*red, 1*alicates, 1*espátula, 1*plástico varilla(negro o blanco).',
      ],
    },
    {
      name: 'STAYER 1.2381 Equipo de Soldadura Inverter, Super Plus 160 GEK',
      category: 'Soldadores',
      slug: 'STAYER-1.2381-Equipo-de-Soldadura-Inverter',
      link: 'https://www.amazon.es/STAYER-1-2381-Equipo-Soldadura-Inverter/dp/B08YRSM21X?_encoding=UTF8&psc=1&refRID=QJGZR3QF2MEDPG5TDGNC&linkCode=ll1&tag=sarria93-21&linkId=3c3853d791a5700d9775c18e59e99d5f&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/soldadores/81zYf8eKdZS._AC_SL1500_.jpg',
      price: 160.0,
      brand: 'Stayer',
      rating: 4.5,
      numReviews: 33,
      countInStock: 1,
      description: [
        'SUELDA EN CONTINUO ELECTRODOS DE 4.0 mm',
        'Factor de marcha super profesional: 100% con aire a 30ºC',
        'Incluye todo lo necesario para empezar a soldar, incluso con usuarios sin experiencia gracias a su dotación y facilidad de uso.',
        'Preparado para soldadura especial TIG mediante electrodo de tungsteno en atmósfera inerte',
        'Apto para todo tipo de trabajos ligeros y medianos en los campos de mantenimiento, construcción y bricolaje.',
        'Prestaciones incomparables en su nivel de precio: 160A en continuo, voltaje en vacío =64Vdc.',
        'Incorpora sistema profesional de refrigeración con estabilidad térmica y máximo rendimiento en su categoría.',
      ],
    },

    {
      name: 'Stanley DN200/8/6 - Compresor de aire',
      category: 'Compresores de aire',
      slug: 'Stanley-DN200/8/6-Compresor-de-aire',
      link: 'https://www.amazon.es/Stanley-DN200-8-6-Compresor/dp/B00IRA7GTS?_encoding=UTF8&refRID=TGE2Z6548S9XKC7K9XAG&th=1&linkCode=ll1&tag=sarria93-21&linkId=fe40de424a22e1e71308728382230a4d&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/compresoresAire/71KbeNPd9rS._AC_SL1500_.jpg',
      price: 130.5,
      brand: 'Stanley',
      rating: 4.4,
      numReviews: 850,
      countInStock: 7,
      description: [
        'Compresor de pistón, 8 bar de presión',
        'De facil uso gracias al encendido on/off en el panel de control con manometro de rapida lectura',
        'Dotado de gancho para colgar accesorios',
        'Grifo de purga de esfera, profesional, con paso aumentado para evitar obstrucciones y bloqueo',
        'Aire aspirado (lts/min): 180',
      ],
    },
    {
      name: 'Bosch compresor de aire a batería EasyPump (batería de 3,0 Ah, 3,6 voltios, función de parada automática, 150 psi, 10,3 bar, LED, recargable mediante cable USB-C, en caja)',
      category: 'Compresores de aire',
      slug: 'Bosch-compresor-de-aire-a-batería-EasyPump',
      link: 'https://www.amazon.es/compresor-EasyPump-autom%C3%A1tica-recargable-mediante/dp/B08HQHW4LS?_encoding=UTF8&psc=1&refRID=TGE2Z6548S9XKC7K9XAG&linkCode=ll1&tag=sarria93-21&linkId=1178b72e2d966a0940ac38c0b3862b42&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/compresoresAire/61TJILXpA5L._AC_SL1000_.jpg',
      price: 85.37,
      brand: 'Bosch Home and Garden',
      rating: 4.5,
      numReviews: 455,
      countInStock: 3,
      description: [
        'Comodidad: La bomba de aire a batería puede utilizarse para inflar neumáticos (automóvil, motocicleta, bicicleta), pelotas y pequeños equipos de agua con hasta 10,3 bar de presión y es adecuada para todas las válvulas estándar, y solo pesa 430 g',
        'Función de parada automática: La bomba de aire ofrece 3 unidades de presión diferentes (psi, bar, kPa) y se apaga automáticamente al alcanzar el valor preestablecido',
        'Pantalla digital y luz LED: la pantalla iluminada muestra la medición en tiempo real, el valor preestablecido y el indicador de estado de la batería. La luz LED ilumina la zona de la válvula',
        'Función de apagado automático: para ahorrar energía, el compresor de aire se apagará automáticamente si no se usa y cuenta con USB-C para recargarlo de forma sencilla',
        'Incluye: EasyPump, cable USB, adaptador de volumen, aguja para bolas, adaptador de válvula Presta, bolsa de tela, en caja',
      ],
    },
    {
      name: 'MICHELIN 9519 Compresor de aire portatil programable, 12 V',
      category: 'Compresores de aire',
      slug: 'MICHELIN-9519-Compresor-de-aire-portatil-programable-12-V',
      link: 'https://www.amazon.es/Michelin-009519-Compresor-Digital-12-V/dp/B00KMZZJWC?_encoding=UTF8&refRID=TGE2Z6548S9XKC7K9XAG&th=1&linkCode=ll1&tag=sarria93-21&linkId=1b88abc98e20865505614aa19f77ac20&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/compresoresAire/51f1fkUfI+L._AC_SL1009_.jpg',
      price: 69.0,
      brand: 'MICHELIN',
      rating: 4.4,
      numReviews: 4000,
      countInStock: 3,
      description: [
        'Compresor digital 12 V/ programable. Inflado de un neumático estándar en 3 minutos',
        'Permite inflar desde 0.05 bar hasta 7 bar. Conexión a la toma del encendedor 12 V. Ideal para automóviles, motos, bicicletas, actividades de ocio (globos, colchones de aire)',
        'Función predeterminada: le permite inflar automáticamente hasta la presión seleccionada en la pantalla digital. El compresor se detiene una vez que se alcanza la presión deseada. Pantalla digital retroiluminada para leer y seleccionar la presión deseada',
        'Lámpara de iluminación LED. Toma de 12 V y USB para alimentar apartos electrónicos. Almacenaje para la manguera de inflado. Manguera de nylon de 60 cm',
        'Punta de latón para un sellado perfecto en la válvula del Neumático. Se suministra con puntas para inflar neumáticos de bicicleta, globos y juguetes inflables. Almacenamiento de las puntas en la parte posterior del compresor. Presión de aire: 16 l/min. Ruidos y vibraciones mínimas',
      ],
    },
    {
      name: 'MICHELIN - Inflador con medidor de presión de neumáticos - Presión máxima: 10 bar - Homologado, negro, norme',
      category: 'Compresores de aire',
      slug: 'MICHELIN-Inflador-con-medidor-de-presión-de-neumáticos',
      link: 'https://www.amazon.es/Michelin-CA-6211860003-Inflador-presi%C3%B3n-homologado/dp/B00SRX9MQA?_encoding=UTF8&refRID=TGE2Z6548S9XKC7K9XAG&th=1&linkCode=ll1&tag=sarria93-21&linkId=0a99c2ee0fc1e30ae003e62395b907ec&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/compresoresAire/712uua9pfmL._AC_SL1500_.jpg',
      price: 67.44,
      brand: 'MICHELIN',
      rating: 4.3,
      numReviews: 429,
      countInStock: 1,
      description: [
        'Pistola de inflado con manómetro ideal para inflar los neumáticos de coches o bicicletas',
        'Alta tasa de flujo de aire para un perfecto control de la inflación',
        'Tamaño compacto y mango aislante para un funcionamiento seguro y fácil, versión aprobada',
        'Herramienta neumática para un compresor de aire',
        'Presión máxima: 10 bar',
        'Unidades: 1.0',
        'Número de items: 1',
      ],
    },
    {
      name: 'Black+Decker ASI300-QS - Compresor de aire, 160 PSI, 11 bar, Fuente de alimentación: Cable eléctrico, Rojo/Negro',
      category: 'Compresores de aire',
      slug: 'Black+Decker-ASI300-QS-Compresor-de-aire',
      link: 'https://www.amazon.es/Black-Decker-ASI300-QS-Compresor-aire/dp/B003A5ZBY2?_encoding=UTF8&refRID=TGE2Z6548S9XKC7K9XAG&th=1&linkCode=ll1&tag=sarria93-21&linkId=cb51261fea3257ccbcfeefecfe631b69&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/compresoresAire/61Tc9ul2hvL._AC_SL1000_.jpg',
      price: 70.0,
      brand: 'Black+Decker',
      rating: 4.2,
      numReviews: 4522,
      countInStock: 7,
      description: [
        'Compresor de aire de 160 PSI con mucha potencia, responde a las tareas de inflado más frecuentes como inflado de ruedas de bicicletas, motos, neumáticos grandes y equipamiento de deporte como balones',
        'El compresor de aire puede ser utilizado en casa con electricidad (CA) o en vehículos (CC)',
        'Sencilla rueda de selección de presión que ajusta de manera precisa la presión deseada para realizar la tarea de trabajo',
        'Su diseño compacto permite guardarlo fácilmente en el maletero del coche/ estantería/ armario',
        'Incluye: 18 metros de cable CC, 31 metros de cable 12V (CA), 3 accesorios para equipamiento de deporte y manguera con accesorios para neumáticos de coche',
      ],
    },

    {
      name: 'ATHLON TOOLS Carretilla plegable de aluminio | zona de carga con almohadillas antideslizantes | ruedas con bandas de rodadura suaves | incl. 2 cuerdas extensibles',
      category: 'Carretillas',
      slug: 'ATHLON-TOOLS-Carretilla-plegable-de-aluminio',
      link: 'https://www.amazon.es/ATHLON-TOOLS-Carretilla-almohadillas-antideslizantes/dp/B07QN5JQG9?_encoding=UTF8&psc=1&refRID=35D07WK77N1YWC2VVG6B&linkCode=ll1&tag=sarria93-21&linkId=99a8c09f9664b63d6ba797448b9f3a8b&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/carretillas/71sUmgjClRL._AC_SL1500_.jpg',
      price: 49.9,
      brand: 'ATHLON TOOLS',
      rating: 4.5,
      numReviews: 1719,
      countInStock: 0,
      description: [
        ' 𝗜𝗗𝗘𝗔𝗟 𝗣𝗔𝗥𝗔 𝗧𝗥𝗔𝗡𝗦𝗣𝗢𝗥𝗧𝗔𝗥 𝗖𝗔𝗥𝗚𝗔𝗦 𝗦𝗜𝗡 𝗘𝗦𝗙𝗨𝗘𝗥𝗭𝗢: La carretilla es perfecta para todas las tareas de transporte relacionadas con las compras, el hogar o el jardín.',
        ' 𝗘𝗦𝗧𝗔𝗕𝗟𝗘 𝗬 𝗟𝗜𝗚𝗘𝗥𝗔: Todas las piezas de transporte son de aluminio robusto. La capacidad de carga máxima es de 70 kg. ¡Tan solo pesa 3,2 kg! La zona de carga mide 39 x 28 cm.',
        ' 𝗦𝗨𝗔𝗩𝗘𝗦 𝗬 𝗕𝗜𝗘𝗡 𝗣𝗘𝗡𝗦𝗔𝗗𝗔𝗦: Las ruedas y las suspensiones de las ruedas están completamente montadas con rodamientos de bolas y, por lo tanto, son especialmente suaves y duraderas. Las bandas de rodadura suaves y grises de las ruedas giran silenciosamente y no marcan las superficies.',
        ' 𝗖𝗢𝗠𝗣𝗔𝗖𝗧𝗔 𝗬 𝗗𝗘 𝗗𝗜𝗠𝗘𝗡𝗦𝗜𝗢𝗡𝗘𝗦 𝗥𝗘𝗗𝗨𝗖𝗜𝗗𝗔𝗦: La carretilla puede desplegarse y plegarse en cuestión de segundos. Cabe en cada maletero, cobertizo de jardín y trastero. El asa telescópica extra larga (110cm) cuenta con un ajuste rápido y las ruedas se pliegan y se despliegan automáticamente junto con la zona de carga.',
        ' 𝗤𝗨É 𝗩𝗜𝗘𝗡𝗘 𝗜𝗡𝗖𝗟𝗨𝗜𝗗𝗢: Una carretilla de aluminio completamente montada, dos cuerdas extensibles para asegurar la carga, una factura digital y un servicio de atención al cliente atento y servicial.',
      ],
    },
    {
      name: 'Stanley SXWTD-HT523 - Carretilla de mano de acero, 200 kg, Amarilla',
      category: 'Carretillas',
      slug: 'Stanley-SXWTD-HT523-Carretilla',
      link: 'https://www.amazon.es/Stanley-SXWTD-HT523-Steel-Hand-Truck/dp/B01N95171E?_encoding=UTF8&refRID=35D07WK77N1YWC2VVG6B&th=1&linkCode=ll1&tag=sarria93-21&linkId=3a5de79629b45e6bf7b3a12d3a70870e&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/carretillas/51NB8SH6kuL._AC_SL1000_.jpg',
      price: 75.73,
      brand: 'Stanley',
      rating: 4.4,
      numReviews: 3119,
      countInStock: 3,
      description: [
        'Carretilla 200KG - extremadamente robusta',
        'Las ruedas son silenciosas',
        'Ideal para profesionales, pero también para cargas, entregas, reubicaciones y la exigente mejora del hogar en casa y jardín',
      ],
    },
    {
      name: 'Hivexagon Carrito de Equipaje Plegable, Compacto Ligero Duradero de Aluminio Capacidad de Carga de 40kg/88lbs para Equipaje, Viajes, de compras, Uso en Oficina y Transporte HG405',
      category: 'Carretillas',
      slug: 'Hivexagon-Carrito-de-Equipaje-Plegable',
      link: 'https://www.amazon.es/Hivexagon-Equipaje-Plegable-Capacidad-Transporte/dp/B07R8BQ6V3?_encoding=UTF8&psc=1&refRID=35D07WK77N1YWC2VVG6B&linkCode=ll1&tag=sarria93-21&linkId=aa7ef7989c2f68b36ec5f047e9998ed0&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/carretillas/618lpV9TV8L._SL1001_.jpg',
      price: 27.99,
      brand: 'Hivexagon',
      rating: 4.1,
      numReviews: 229,
      countInStock: 0,
      description: [
        'Dimensiones del cuerpo: 15.7" x 10.6" x 3.5"/40 x 27 x 9cm, Peso: 2.75 libras. / 1.25kg. Plegable para transportarlo y guardarlo fácilmente.',
        'Estructura de altura ajustable para 3 tamaños: 40cm/15.7”, 60cm/23.6”, 95cm/37.4”.Compatible con productos de diferentes tallas',
        'Incluye 2 cuerdas elásticas con gancho para fijar y proteger el equipaje',
        'Construido con aluminio sólido y ligero, anti corrosivo y anti oxidable. Ruedas de mayor tamaño (8cm de diámetro) para mejorar su manejo.',
        'Construcción resistente y ligera, se abre y se cierra en cuestión de segundos con un manejo sencillo.',
      ],
    },
    {
      name: 'Meister 8985730 - Carretilla, 45 kg, mini, plegable',
      category: 'Carretillas',
      slug: 'Meister-8985730-Carretilla',
      link: 'https://www.amazon.es/Meister-8985730-Carretilla-45-plegable/dp/B01MS1Q3QT?_encoding=UTF8&psc=1&refRID=35D07WK77N1YWC2VVG6B&linkCode=ll1&tag=sarria93-21&linkId=9594710adf7d443da66b03ee1778cb62&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/carretillas/71aIYrucbPL._AC_SL1500_.jpg',
      price: 48.67,
      brand: 'Meister',
      rating: 4.0,
      numReviews: 826,
      countInStock: 1,
      description: [
        'Capacidad de carga: máx. 45 kg.',
        'Medidas cajón: 320 x 234 mm.',
        'Con correa ajustable para la fijación de la carga.',
        'Mango de altura ajustable individualmente.',
        'Práctica función plegable para un almacenamiento compacto.',
      ],
    },
    {
      name: 'DURHAND Carretilla Plegable para Escalera con Ruedas Carga 150kg Carretilla de Mano Portátil para Entrega Almacenes Mercado Viajar Mudarse',
      category: 'Carretillas',
      slug: 'DURHAND-Carretilla-Plegable',
      link: 'https://www.amazon.es/DURHAND-Carretilla-Plegable-Escalera-Almacenes/dp/B081511DHT?_encoding=UTF8&psc=1&refRID=35D07WK77N1YWC2VVG6B&linkCode=ll1&tag=sarria93-21&linkId=a06afc15f8d6bdb0a18eaea633976739&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/carretillas/616KnVzTapL._AC_SL1500_.jpg',
      price: 69.99,
      brand: 'DURHAND',
      rating: 4.0,
      numReviews: 67,
      countInStock: 1,
      description: [
        ' CARRETILLA PLEGABLE PARA ESCALERAS. Gracias al diseño de sus 6 ruedas, subir y bajar por escaleras cosas pesadas resulta mucho más cómodo.',
        ' 3 SUPERFICIES DE APOYO DE LA CARGA. Además de la base donde colocar la carga, también dispone de dos superficies adicionales a los lados, para asegurar la estabilidad de la mercancía durante el transporte.',
        ' ESTRUCUTRA REGULABLE EN ALTURA. Su estructura se puede regular en altura para que el manillar quede a la altura óptima de cada usuario.',
        ' PLEGABLE. Cuando no se utiliza, se puede guardar fácilmente.',
        ' MEDIDAS: 60x45x109cm (LxANxAL). Soporta un máximo de 150kg.',
      ],
    },

    {
      name: 'WOLFPACK LINEA PROFESIONAL Transpaleta De Almacen Ruedas Poliuretano 2,5 T.',
      category: 'Transpaletas',
      slug: 'WOLFPACK-LINEA-PROFESIONAL-Transpaleta-De-Almacen-Ruedas-Poliuretano',
      link: 'https://www.amazon.es/Transpaleta-Almacen-Ruedas-Nylon-T/dp/B01MZ1LTPF?_encoding=UTF8&psc=1&refRID=KXKQARH1AAZ85YT0NPR8&linkCode=ll1&tag=sarria93-21&linkId=e9bca18198c18a8a0dc23518049f3cd6&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/transpaletas/51-a-qhL++L._AC_SL1372_.jpg',
      price: 369.45,
      brand: 'WOLFPACK LINEA PROFESIONAL',
      rating: 0,
      numReviews: 0,
      countInStock: 1,
      description: [
        'Capacidad de carga: 2.5 toneladas.',
        'Estructura de acero especial de alta resistencia.',
        'Timón con barra envolvente de seguridad y diseño ergonómico.',
        'Palanca de maniobra accionada por bomba hidráulica.',
        'Cilindro hidráulico con accesorios antiaceite que aporta estanqueidad del líquido.',
      ],
    },
    {
      name: 'Ayerbe transpaletas - Transpaleta ay-2500-thn ruedas nylon',
      category: 'Transpaletas',
      slug: 'Ayerbe-transpaletas-Transpaleta-ay-2500-thn',
      link: 'https://www.amazon.es/Ayerbe-transpaletas-Transpaleta-ay-2500-thn-ruedas/dp/B00CWZRFLS?_encoding=UTF8&psc=1&refRID=KXKQARH1AAZ85YT0NPR8&linkCode=ll1&tag=sarria93-21&linkId=83c8fe1953e3aa042eed7e00897d895c&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/transpaletas/51aa-CUFuKL._AC_SL1050_.jpg',
      price: 345.0,
      brand: 'Ayerbe',
      rating: 4.4,
      numReviews: 6,
      countInStock: 5,
      description: [
        'Transpaleta manual con capacidad de 2.500 Kgs AY-2500-THN.',
      ],
    },
    {
      name: 'Transpaleta Manual 2500 kg, Horquillas 1150x525 mm, Ruedas Poliuretano/Rodillos Nylon',
      category: 'Transpaletas',
      slug: 'Transpaleta-Manual-2500 kg',
      link: 'https://www.amazon.es/Pramac-Transpaleta-manual-2500-1150x525/dp/B07BYV79WC?_encoding=UTF8&psc=1&refRID=KXKQARH1AAZ85YT0NPR8&linkCode=ll1&tag=sarria93-21&linkId=28aba0742103948b215f01b0d22180f9&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/transpaletas/31IIr8eqWPS.jpg',
      price: 409.0,
      brand: 'Pramac',
      rating: 5.0,
      numReviews: 1,
      countInStock: 1,
      description: [
        'Ruedas de poliuretano',
        '2500kg de capacidad de carga',
        'Horquillas: 1150x525mm',
        'Rodillos Dobles de nylon',
      ],
    },
    {
      name: 'Einhell palé Transpaleta TC de PT 2500 (carga 2500 kg, tenedor Altura 80 – 190 mm, estructura resistente en acero, ruhige unidad eigenschaft el Poco rodadura)',
      category: 'Transpaletas',
      slug: 'Einhell-palé-Transpaleta-TC-de-PT-2500',
      link: 'https://www.amazon.es/Einhell-Transpaleta-estructura-resistente-eigenschaft/dp/B01NCIJSFB?_encoding=UTF8&psc=1&refRID=KXKQARH1AAZ85YT0NPR8&linkCode=ll1&tag=sarria93-21&linkId=0011660f131409bdcd1fc55459ea8217&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/transpaletas/61dkfU2y7IL._AC_SL1500_.jpg',
      price: 388.5,
      brand: 'Einhell',
      rating: 4.2,
      numReviews: 11,
      countInStock: 3,
      description: [
        'Elevador de la paleta robusta para cualquier taller profesional con seguridad autodescargables y integ. palanca de cambios con tres funciones',
        'Retorno automático de la perla en la vertical. fuerza de carga 2500 kg, tenedor, Altura 80 – 190 mm, robusta construcción de acero, tranquilo unidad característica al poco rodadura',
        'Fiable, mantenimiento hidráulica y construcción resistente con acero soldado marco',
        'repujadas, gabelzinken reforzadas para la carga fiable de grabación',
        'Características de funcionamiento tranquilo y bajo rodadura mediante rodamiento de bolas y revestimiento de PU en asiento y arrastre ruedas',
      ],
    },
    {
      name: 'Ayerbe M110167 - Traspaleta 2500 kg ruedas de vulkollan',
      category: 'Transpaletas',
      slug: 'Ayerbe-M110167-Traspaleta-2500-kg-ruedas-de-vulkollan',
      link: 'https://www.amazon.es/Ayerbe-M110167-Traspaleta-ruedas-vulkollan/dp/B00SP96PNO?_encoding=UTF8&psc=1&refRID=KXKQARH1AAZ85YT0NPR8&linkCode=ll1&tag=sarria93-21&linkId=ad4508069232540b60bbd176ef1026d2&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/transpaletas/51tUVKou28L._AC_SL1050_.jpg',
      price: 435.13,
      brand: 'Ayerbe',
      rating: 4.8,
      numReviews: 15,
      countInStock: 1,
      description: [
        'Ruedas PU y una capacidad máxima de 2500 kg',
        '4 rodillos de Ø 80 mm 2 ruedas de Ø 200 mm',
        'Válvula de seguridad por sobrecarga y sistema de descenso controlado',
        'Pistón cromado. Normativas: CE, GS y TÜV',
      ],
    },

    {
      name: 'Makinex 0004662 Carretilla De Mano Motorizada',
      category: 'Carretillas Elevadoras',
      slug: 'Makinex-0004662',
      link: 'https://www.amazon.es/Makinex-0004662-Carretilla-Mano-Motorizada/dp/B07CYTV9MG?_encoding=UTF8&psc=1&refRID=207KA2K3NFDZAD6J4124&linkCode=ll1&tag=sarria93-21&linkId=f0f5786593e25ca4ba842dd4ba869f79&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/carretillasElevadoras/51Qp6huG5nL.jpg',
      price: 0.0,
      brand: 'Makinex',
      rating: 0,
      numReviews: 0,
      countInStock: 1,
      description: [
        'Capacidad de elevación 140 Kgs',
        'Altura de elevación máxima con el accesorio del gancho 1,9 metros',
        'Altura de elevación máxima con el accesorio tenedor 1,55 metros',
      ],
    },
    {
      name: 'Ayerbe - Apilador manual ay-2500-apm 1000kg',
      category: 'Carretillas Elevadoras',
      slug: 'Ayerbe-Apilador-manual-ay-2500-apm-1000kg',
      link: 'https://www.amazon.es/Ayerbe-Apilador-manual-ay-2500-apm-1000kg/dp/B01MTFZY6K?_encoding=UTF8&psc=1&refRID=207KA2K3NFDZAD6J4124&linkCode=ll1&tag=sarria93-21&linkId=ad4b4190ffd156ce896d08af1f64480d&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/carretillasElevadoras/41eqdNt892L._AC_.jpg',
      price: 1645.95,
      brand: 'Ayerbe',
      rating: 0,
      numReviews: 0,
      countInStock: 1,
      description: ['Apilador manual ay-2500-apm 1000kg'],
    },
    {
      name: 'TAP 47004 Apilador manual - fuerza 400kg',
      category: 'Carretillas Elevadoras',
      slug: 'TAP-47004-Apilador-manual-fuerza-400kg',
      link: 'https://www.amazon.es/TAP-47004-Apilador-manual-fuerza/dp/B084N4TW19?_encoding=UTF8&psc=1&refRID=207KA2K3NFDZAD6J4124&linkCode=ll1&tag=sarria93-21&linkId=f2b5407f603466fd7b7f246536a2e660&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/carretillasElevadoras/71WsEAIIb9L._SL1500_.jpg',
      price: 0.0,
      brand: 'TAP FRANCE',
      rating: 0.0,
      numReviews: 0,
      countInStock: 0,
      description: [
        'Se levanta con una pedal; se baja con una palanca que permite una maniobra muy precisa; frenos accionados con pedal',
        'Bastidor y horquillas de acero reforzado, acabado pintado epoxi amarillo; bandeja amovible de acero reforzado, tubos cromados',
        'Ruedas de dirección ( diámetro 127x40 mm) de fundición con banda de poliuretano, giran hacia los 360°; ruedecillas de larguero ( diámetro 75x40 mm) de acero con banda de poliuretano',
        'Capacidad de carga: 400 kg.distancia exterior de las horquillas: 576 mm; altura de levantamiento mínima/máxima: 85/1415 mm; medidas de las horquillas (lxanchxalt): 1165x160x50 mm',
      ],
    },
    {
      name: 'APILADOR MANUAL DE 1000KG DE CAPACIDAD 1600MM DE ELEVACIÓN',
      category: 'Carretillas Elevadoras',
      slug: 'APILADOR-MANUAL-DE-1000KG-DE-CAPACIDAD-1600MM-DE-ELEVACIÓN',
      link: 'https://www.amazon.es/Disset-elevaci%C3%B3-MX10-16-APILADOR/dp/B072JJVWDR?_encoding=UTF8&psc=1&refRID=207KA2K3NFDZAD6J4124&linkCode=ll1&tag=sarria93-21&linkId=c450c7f76c681b6e9e7e52002a90a45a&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/carretillasElevadoras/41IyjGz-2nL.jpg',
      price: 1190.0,
      brand: 'Disset elevació',
      rating: 0.0,
      numReviews: 0,
      countInStock: 1,
      description: ['APILADOR MANUAL NUEVO', 'Modelo MX10/16'],
    },
    {
      name: 'Apilador Manual de 1000kg de capacidad y 1600mm de elevación [Clase de eficiencia energética A]',
      category: 'Carretillas Elevadoras',
      slug: 'Apilador-Manual-de-1000kg-de-capacidad-y-1600mm-de-elevación-PRAMAC',
      link: 'https://www.amazon.es/hidr%C3%A1ulico-carretilla-elevadora-horquilla-elevaci%C3%B3n/dp/B00OYZ9KNA?_encoding=UTF8&psc=1&refRID=207KA2K3NFDZAD6J4124&linkCode=ll1&tag=sarria93-21&linkId=d390daa89884243f16055fa896e92275&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/carretillasElevadoras/41PbOmMMWZL._AC_.jpg',
      price: 1190.0,
      brand: 'Pramac',
      rating: 0.0,
      numReviews: 0,
      countInStock: 1,
      description: [
        'Apilador Manual de 1000kg de capacidad y 1600mm de elevación [Clase de eficiencia energética A]',
      ],
    },

    {
      name: 'Intex 28272NP Small Frame - Piscina desmontable, 300 x 200 x 75 cm, 3.834 litros, azul',
      category: 'Piscinas desmontables',
      slug: 'Intex-28272NP-Small-Frame-Piscina-desmontable',
      link: 'https://www.amazon.es/Intex-28272NP-Small-Frame-desmontable/dp/B001IWNDDA?_encoding=UTF8&refRID=9BGXWGCA2MAEVJAYYCTR&th=1&linkCode=ll1&tag=sarria93-21&linkId=efff86aada0d21b5efb3f4855ab76fb6&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/piscinasDesmontables/71hukYKs-KL._AC_SL1500_.jpg',
      price: 129.0,
      brand: 'Intex',
      rating: 4.6,
      numReviews: 23622,
      countInStock: 1,
      description: [
        'Piscina rectangular desmontable tubular Intex Small Frame con estructura metálica, medidas: 300 x 200 x 75 cm, capacidad: 3.834 litros, para 6 personas (+ 6 años)',
        'Con estructura metálica de fácil montaje, compuesta por piezas de acero con epoxy antióxido, lista para ser usada en aproximadamente 30 minutos',
        'Lona con tecnología tricapa Super-Tough, cuenta con tapón de vaciado conectable a manguera de jardín para facilitar el desagüe',
        'No incluye depuradora pero cuenta con conexiones de 32 mm para poder adaptársela',
        'Recomendados para espacios pequeños gracias a su diseño, para una óptima utilización y durabilidad se aconseja seguir las instrucciones del manual',
      ],
    },
    {
      name: 'Bestway 56416 - Piscina Desmontable Tubular Steel Pro Max 366x76 cm Depuradora de Cartucho 1.249 litros/hora',
      category: 'Piscinas desmontables',
      slug: 'Bestway-56416-Piscina-Desmontable-Tubular',
      link: 'https://www.amazon.es/Bestway-56416-Desmontable-depuradora-Cartucho/dp/B014FHBB4W?_encoding=UTF8&refRID=9BGXWGCA2MAEVJAYYCTR&th=1&linkCode=ll1&tag=sarria93-21&linkId=c6dd207aa4eafb006f53c7d38743c663&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/piscinasDesmontables/91vDhbmeTWL._AC_SL1500_.jpg',
      price: 167.5,
      brand: 'Bestway',
      rating: 4.3,
      numReviews: 471,
      countInStock: 1,
      description: [
        'Fácil montaje – Pese a su resistente marco de acero, esta piscina elevada se puede montar sin herramientas',
        'Muy duradera – La piscina para jardín cuenta con robustas paredes laterales de resistente material Tritech',
        'Agua limpia – Con la depuradora incluida, el agua de la piscina tubular se puede limpiar sin esfuerzo',
        'Válvula integrada – Tras el verano, la piscina portátil se vacía cómodamente con la válvula de drenaje',
        'El envío incluye – Piscina redonda desmontable Steel Pro MAX de Bestway, depuradora de filtro, cartucho de filtro y parche de reparación autoadhesivo; material: TriTech, medidas: 366x366x76 cm, azul',
      ],
    },
    {
      name: 'Intex 28202NP - Piscina redonda metal frame intex 305x76 cm 4485 litros + depuradora',
      category: 'Piscinas desmontables',
      slug: 'Intex-28202NP-Piscina-redonda-metal',
      link: 'https://www.amazon.es/Intex-Metal-Frame-Piscina-desmontable/dp/B00FCT255C?_encoding=UTF8&refRID=9BGXWGCA2MAEVJAYYCTR&th=1&linkCode=ll1&tag=&linkId=7a926e2ff7d913c272fbe637a37e8c4f&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/piscinasDesmontables/61NmriFzPFS._AC_SL1500_.jpg',
      price: 195.0,
      brand: 'Intex',
      rating: 4.4,
      numReviews: 6678,
      countInStock: 10,
      description: [
        'Piscina redonda desmontable Intex Metal Frame, medidas 305x76 cm, capacidad para 4485 litros de agua',
        'Estructura compuesta por tubos de acero recubierto con epoxy antióxido que forman un armazón compacto de alta resistencia',
        'Lona fabricada con PVC laminado de tres capas con tecnología SuperTough para mayor durabilidad',
        'Incluye depuradora de cartucho con filtro tipo H con capacidad de filtración de 1250 litros/hora',
        'Dispone de tapón de vaciado con conexión a una manguera de jardín para un drenaje cómodo y fácil',
      ],
    },
    {
      name: 'INTEX-57100NP Piscina infantil hinchable cuadrada, colores aleatorios, 86 x 86 x 25 cm, 1 unidad',
      category: 'Piscinas desmontables',
      slug: 'INTEX-57100NP-Piscina-infantil-hinchable-cuadrada',
      link: 'https://www.amazon.es/Intex-infantil-hinchable-cuadrada-surtidos/dp/B00C6A5OOO?_encoding=UTF8&psc=1&refRID=9BGXWGCA2MAEVJAYYCTR&linkCode=ll1&tag=sarria93-21&linkId=e336687c3db3c549d5ee00a76b5c58ec&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/piscinasDesmontables/71VIDjgR4rL._AC_SL1500_.jpg',
      price: 11.99,
      brand: 'Intex',
      rating: 4.5,
      numReviews: 5610,
      countInStock: 9,
      description: [
        'Piscina hinchable para niños con medidas 86x86x25 cm, es de forma cuadrada y fabricada en vinilo resistente con suelo hinchable suave para mayor comodidad',
        'Diseño lateral formado por dos aros hinchables, piscina disponible en dos modelos surtidos: rosa o verde lima',
        'Tiene capacidad para 57 litros (17 cm de alto) y está recomendada para bebés de entre 1 y 3 años, uso recomendado bajo supervisión de un adulto',
        'Para inflar y desinflar más rápido la piscina es aconsejable utilizar un hinchador manual o eléctrico (se venden aparte)',
        'La piscina incluye kit con parche para reparar pequeños poros o pinchazos en la lona',
      ],
    },
    {
      name: 'Bestway 57270 - Piscina Desmontable Autoportante Fast Set 305x76 cm Depuradora de cartucho de 1.249 litros/hora',
      category: 'Piscinas desmontables',
      slug: 'Bestway-57270-Piscina-Desmontable-Autoportante',
      link: 'https://www.amazon.es/Lola-Home-Bestway-57268-depuradora/dp/B014FHC96G?_encoding=UTF8&psc=1&refRID=9BGXWGCA2MAEVJAYYCTR&linkCode=ll1&tag=sarria93-21&linkId=79ebf2b2a250f9dbe8ffbde87fdf9d46&language=es_ES&ref_=as_li_ss_tl',
      image: '/images/piscinasDesmontables/81CST2YJICL._AC_SL1500_.jpg',
      price: 79.96,
      brand: 'Bestway',
      rating: 3.8,
      numReviews: 3503,
      countInStock: 15,
      description: [
        'La forma redonda proporciona una instalación más fácil, una mayor estabilidad y menos espacio desperdiciado',
        'Uso inmediato – Este completo conjunto de piscina para jardín se hincha rápidamente',
        'La válvula de drenaje con control de flujo incorporada y el adaptador incluido le permiten conectar una manguera de jardín para un drenaje simple y rápido de la piscina',
        'Las paredes están hechas con Tritech, 3 capas de PVC y poliéster resistentes',
        'Agua limpia – Con la depuradora de cartucho, la piscina se limpia de forma rápida y eficiente',
      ],
    },
  ],

  categoriesList: [
    {
      name: 'Taladro Percutor',
      image: '/images/taladrosPercutor/71pXagaxQ1L._AC_SL1500_.jpg',
      slug: 'taladro-percutor',
    },

    {
      name: 'Taladros Atornilladores',
      image: '/images/taladrosAtornillador/81Kr8gxqcsL._AC_SL1500_.jpg',
      slug: 'taladro-atornillador',
    },

    {
      name: 'Amoladoras',
      image: '/images/amoladoras/81M6s7FW1uL._AC_SL1500_.jpg',
      slug: 'amoladoras',
    },

    {
      name: 'Lijadoras',
      image: '/images/lijadoras/71rSLwgwSgL._AC_SL1500_.jpg',
      slug: 'lijadoras',
    },

    {
      name: 'Soldadores',
      image: '/images/soldadores/61lpNdFHpdL._SL1500_.jpg',
      slug: 'soldadores',
    },

    {
      name: 'Compresores de aire',
      image: '/images/compresoresAire/71KbeNPd9rS._AC_SL1500_.jpg',
      slug: 'compresores-aire',
    },

    {
      name: 'Carretillas',
      image: '/images/carretillas/71GEg+AaGaL._SL1500_.jpg',
      slug: 'carretillas',
    },

    {
      name: 'Transpaletas',
      image: '/images/transpaletas/31IIr8eqWPS.jpg',
      slug: 'transpaletas',
    },

    {
      name: 'Carretillas Elevadoras',
      image: '/images/carretillasElevadoras/41eqdNt892L._AC_.jpg',
      slug: 'carretillas-elevadoras',
    },

    {
      name: 'Piscinas desmontables',
      image: '/images/piscinasDesmontables/71hukYKs-KL._AC_SL1500_.jpg',
      slug: 'piscinas-desmontables',
    },
  ],
};

export default data;
