const data = {
  products: [
    {
      name: 'BLACK+DECKER BEH200-QS Taladro percutor con cable 500W, 230V, incluye empuñadura lateral, 500 W',
      category: 'Taladro Percutor',
      slug: 'black+decker-BEH200-QS',
      image: '/images/taladrosPercutor/81LuqiWs53L._AC_SL1500_.jpg',
      price: 29.5,
      brand: 'Black+Decker',
      rating: 4.5,
      numReviews: 4059,
      countInStock: 24,
      description: [
        'Taladro percutor con cable de 500 W y portabrocas sin llave de 13 mm',
        'Acción percutora de 49.300 imp. adecuado para perforar en mampostería',
        'Sistema reversible y botón de bloqueo para mayor ergonomía y comodidad',
        'El motor de velocidad variable de 0-2.900 rpm proporciona un arranque controlado y preciso',
        'Incluye empuñadura lateral',
      ],
    },
    {
      name: 'Bosch EasyImpact 550 - Taladro percutor (550 W, empuñadura adicional, tope de profundidad, maletín)',
      category: 'Taladro Percutor',
      slug: 'Bosch-EasyImpact-550-Taladro-percutor',
      image: '/images/taladrosPercutor/61uJKO20ZkL._AC_SL1024_.jpg',
      price: 39.55,
      brand: 'Bosch Home and Garden',
      rating: 4.6,
      numReviews: 4015,
      countInStock: 29,
      description: [
        'Potente y compacta herramienta que facilita los trabajos de perforación',
        'Perforar nunca fue tan sencillo: gracias a su bajo peso y su compacto y ergonómico diseño, el manejo de la herramienta resulta especialmente cómodo y sencillo',
        'Potencia de perforación elevada a pesar de la construcción compacta, con independencia del material, incluso en hormigón',
        'Portabrocas de sujeción rápida de dos casquillos para cambio de herramienta sencillo',
        'Control electrónico del número de revoluciones Bosch: la «aceleración» de 50 al máximo con el pulsador de conmutación le permite trabajar de forma precisa, por ejemplo, al inicio de la perforación de superficies lisas o en trabajos de atornillado',
        'Compatible con el Drill Assistant de Bosch para un trabajo aún más preciso: determinación sencilla de la profundidad de perforación y trabajo sin polvo (opcionalmente, disponible como accesorio)',
      ],
    },
    {
      name: 'Martillo Percutor, Martillo Perforador, 5J Energía de Impacto, SDS Plus Mandril, 4 Funciones en 1 con Embrague de Seguridad, Utilizado para Concreto, Metal y Piedra - TRH02A',
      category: 'Taladro Percutor',
      slug: 'Martillo-Percutor-TRH02A',
      image: '/images/taladrosPercutor/71mLxSjsn9S._AC_SL1500_.jpg',
      price: 69.99,
      brand: 'TACK',
      rating: 3.4,
      numReviews: 7,
      countInStock: 50,
      description: [
        '[Potente Motor]: El martillo perforador cuenta con un motor de 1050 W, 5J energía de impacto que se puede proporcionar fuerza de propulsión y hacer agujeros profundos en poco tiempo. El diseño del martillo perforador tiene 4350 BPM, 1050 RPM y su potente mecanismo, que se puede hacer agujeros incluso en los materiales duros. *OJOS: El mandril SDS solo se usa en taladro eléctrico.*',
        '[Cambio Rápido]: La portabroca no se necesita llave, por eso, sea más conveniente cambiar los accesarios, ahorrando tiempo y mejorando la eficiencia del trabajo. El portabrocas SDS-Plus se puede reemplazar por otras portabrocas, que tiene una precisión más alta. El SDS-puls guía la broca para posicionarla precisamente, evita agitación de la broca o la desviación de la posición de perforación y completa la tarea de perforación con mayor facilidad.',
        '[Cuatro Funciones en1]: El interruptor de botón se puede cambiar fácilmente las funciones. La máquina puede cambiarse fácilmente entre las funciones de solo perforación, perforación con percusión y solo percusión. Además, se controla la dirección de cincel plano. El mandril SDS solo se usa en taladro eléctrico.',
        '[Menos Fatiga]: Debido a la absorción de impactos (VDT) y la superficie de agarre suave del mango, el trabajo sería cómodo. El embrague integrado se reduce la reacción y la vibración cuando la broca está atascada para la seguridad en trabajos. Además, su peso relativamente ligero, la máquina podría controlarse bien.',
        '[Accesorios Abundantes]: 1 x Martillo percutor, 3 x Brocas (8, 10, 12 mm), 1 x Cincel Plano (14 x 250 mm), 1 x Cincel de Punta (14 x 250 mm), 1 x Portabrocas 13 mm, 2 x Cepillos de Carbón, 1 x 360 ° Mango Giratorio, 1 x Medidor de Profundidad, 1 x Llave de Broca, 1 x Tubo de Aceite, 1 x Cubierta Antipolvo, 1 x Caja de Almacenamiento, 1 x Instrucciones de Funcionamiento',
      ],
    },
    {
      name: 'Makita HP457DWE - Taladro Percutor A Bateria 18V Litio-Ion 1.5 Ah [Clase de eficiencia energética A]',
      category: 'Taladro Percutor',
      slug: 'Makita-HP457DWE-Taladro-Percutor',
      image: '/images/taladrosPercutor/61-h3jRAYEL._AC_SL1024_.jpg',
      price: 150.51,
      brand: 'Makita',
      rating: 4.6,
      numReviews: 1483,
      countInStock: 45,
      description: [
        'Tiempo de carga 60 minutos aproximadamente con cargador DC18WA',
        'Engranajes metálicos para una perfecta transmisión de la fuerza y mayor durabilidad',
        'Diseño ergonómico con mango antideslizante para un perfecto control de la herramienta y mayor comodidad.',
        '16 posiciones de par de apriete + 1 directa',
        'Porta, brocas autoblocante para un sencillo cambio de la herramienta con sólo una mano',
      ],
    },
    {
      name: 'BLACK+DECKER BCK24D2S-QW - Taladro Percutor 18V (21.000 ipm) y amoladora 125 mm 18V, con 2 baterías litio 2Ah y bolsa de transporte',
      category: 'Taladro Percutor',
      slug: 'BLACK+DECKER-BCK24D2S-QW-Taladro-Percutor',
      image: '/images/taladrosPercutor/717-873XtCL._AC_SL1500_.jpg',
      price: 149.99,
      brand: 'Black+Decker',
      rating: 4.2,
      numReviews: 2565,
      countInStock: 2,
      description: [
        'Taladro percutor 18v a batería litio con porta brocas de 10 mm y 10 + 1 posiciones de apriete',
        'Acción percutora de 21.000 ipm (impactos por minuto) ideal para aplicaciones en mampostería y hormigón',
        'Radial de 125 mm a batería con 8.600 rpm de velocidad adecuada para tareas de corte de azulejos, metales, plásticos o para eliminar óxido y pintura',
        'Amoladora con caja de engranajes de aluminio fundido para una óptima disipación del calor y mayor durabilidad',
        'El kit incluye: 2 baterías litio 18v de 2ah, cargador y bolsa de transporte',
      ],
    },

    {
      name: 'Destornillador Eléctrico 6N.m, HYCHIKA Atornillador Eléctrico Inalámbrico 3.6v Batería 2000mAh (Máximo Par 6 N.m) LED Luz, Mandril Magnético, Cargador con Cable 3.5mm, 20 Accesorios',
      category: 'Taladros Atornilladores',
      slug: 'Destornillador-Eléctrico-6Nm',
      image: '/images/taladrosAtornillador/81Kr8gxqcsL._AC_SL1500_.jpg',
      price: 24.99,
      brand: 'HYCHIKA BETTER TOOLS FOR BETTER LIFE',
      rating: 4.3,
      numReviews: 7657,
      countInStock: 0,
      description: [
        '【Batería de 2000 mAh y carga protección】Nuestro destornillador eléctrico tiene una batería grande de 2000 mAh, que tiene un mayor tiempo de uso que otros productos. Nuestro destornillador eléctrico siempre ejecute a plena potencia y par completo, no habrá una disminución en el par y la potencia debido a la batería baja. El cargador proteger la batería de litio mediante trickle charging, lo que efectivamente extiende la vida útil de la batería de litio(3 años)',
        '【Destornillador eléctrico con 6 N.m Máximo Par y mandril magnético】Operación continua a plena potencia y par completo (puede atornillar 340 tornillos después de cada carga completa), utilizando más ahorro de mano de obra. Adecuados para ensamblar y reparar muebles, aptar para uso DIY, doméstico y de oficina. El portabrocas magnético puede ser más conveniente y el reemplazo rápido de diferentes tipos de accesorios (No necesita apriete de rotación, simplemente conecte o desconecte directamente)',
        '【Atornillador eléctrico con el motor último modelo 2020, 2 formas de usar y 1 LED luz】Los motores más recientes tienen menor consumo de energía, menor generación de calor y mayor vida útil (más de 3 años). Cuando se usa en un espacio pequeño, puede cambiar la forma girando el asa para obtener una experiencia más conveniente. Puede elegir apretar o aflojar con los botones de bloqueo izquierdo y derecho. Tiene luces LED en los extremos delantero, proporciona efectos de iluminación muy claros',
        '【Atornillador eléctrico con 20 Accesorios 】20 accesorios satisfacen la mayoría de sus necesidades, puede consultar nuestra tabla de accesorios para obtener modelos de accesorios detallados. Le recomendamos mucho que utilice el cargador incluido en nuestro paquete, que tiene protección de carga y reduzca el daño a la batería de litio durante cada carga y asegúrese de que la cantidad de carga y descarga cíclica de la batería de litio sea más de 625 veces',
        '【El paquete】No incluye el maletín. 1 x HYCHIKA Destornillador eléctrico 3.6V; 20 x accesorios(Debajo del compartimento dentro de la caja de cartón); 1 x cargador; 1 x manual de usuario en español. (1/4 de pulgada (6,35 mm) con portabrocas magnético, cargar completa en solo 4 horas ( modo de carga protección). Somos fabricante directo de HYCHIKA, por eso, usted no se preocupe nada, cualquer problema contacto con nos directamente, le ayudaremos a resolverlo (7 x 24horas)',
      ],
    },
    {
      name: 'Taladro Atornillador 12V con 2 Baterías, HYCHIKA Destornillador Eléctrico, 30N.m Par Máx, 1.5 Ah Batería, 1 Hora de Carga Rápida, 6PCS Puntas y HSS Brocas, 5PCS Llaves de vaso, 4PCS Brocas de Madera',
      category: 'Taladros Atornilladores',
      slug: 'Taladro-Atornillador-12V-HYCHIKA',
      image: '/images/taladrosAtornillador/81NUfvNm4wL._AC_SL1500_.jpg',
      price: 54.99,
      brand: 'HYCHIKA BETTER TOOLS FOR BETTER LIFE',
      rating: 4.4,
      numReviews: 4216,
      countInStock: 0,
      description: [
        '23 ACCESORIOS RICOS Y DOS BATERIAS DE LITIO - 23 accesorios ricos se satisfecha a la mayoría necesidad de trabajo.Dos baterías de litio pueden mejorar enormemente la eficiencia y el tiempo de trabajo.Adecuado para taladrar agujeros en metal, madera y plástico; tornillos de fijación y aflojamiento.',
        '21+1 AJUSTES DE TORQUE - 21+ 1 par motor sin cable y 12V/1500 mAh Mandril de cierre de 10mm (3/8 ") Aplicable a la perforación del azulejo de piso y metal y la madera, también retiro de los tornillos es esfuerzo y práctico',
        '2 MARCHA DE VELOCIDAD - Ajuste de 2 velocidades e interruptor positivo y negativo. Se pueden seleccionar diferentes velocidades de salida según diferentes escenarios de uso. Con 2 velocidades variables (0-400 rpm y 0-1500 rpm) para la amplia aplicaciones de perforación, atornillado y percusión.',
        'DISEÑO ERGONÓMICO - Cuenta con una luz LED integrada para una iluminación óptima de las áreas de trabajo con oscuridad, el indicador muestra la capacidad de la carga de la batería, fácil de transportar con un clip resistente para el cinturón.',
        'CONTENIDO DEL PAQUETE - 1×HYCHIKA Taladro Atornillador 12V, 2×baterías, 5×Llaves de vaso, 6×Puntas, 6×HSS Brocas, 4×Brocas de Madera, 1×Adaptador, 1×Bolsa de Accesorio, 1×Bolsa de Herramienta.',
      ],
    },
    {
      name: 'Taladro Atornillador 2 Baterías, GOXAWEE 100Pcs Kit Taladro Bateria/Destornillador Eléctrico (2 Baterías de Litio 1500mAh, 30N.m Par Máx, 2 Velocidades, 10mm Portabrocas Automático)',
      category: 'Taladros Atornilladores',
      slug: 'Taladro-Atornillador-2-Baterías-GOXAWEE-100Pcs',
      image: '/images/taladrosAtornillador/71iF7VUX5aL._AC_SL1500_.jpg',
      price: 45.98,
      brand: 'GOXAWEE',
      rating: 4.3,
      numReviews: 220,
      countInStock: 0,
      description: [
        '【 x2 Baterías y carga rápida 】El taladro incluye 2 baterías de iones de litio de 1500 mAh, lo que permite un uso sin restricciones, la batería se carga completamente en tan solo 1 hora.',
        '【 2 Velocidades Taladro Inalámbrico 】Atornillador inalámbrico equipado con ajuste de 2 velocidades a 0-350/ 1350 rpm. El disparador de presión de velocidad variable le permite controlar la velocidad de perforación ● Baja velocidad (0-350 rpm) es ideal para atornillar ● Alta velocidad (0-1350 rpm) es más eficiente para las tareas de perforación.',
        '【 18-30Nm & 15+1 Ajuste de Par 】El destornillador eléctrico le ofrece más de 15 opciones de ajustes precisos para la mayoría de las necesidades diarias; ☛ Gira el círculo del cabezal de perforación para cambiar la velocidad, el par máximo a 30 Nm es ideal para trabajos mas complejos. ▲Perforación máxima: 10 mm (metal) & 15 mm (madera) / Atornillado máximo: 10mm.',
        '【 Diseño Ergonomico & Personalidad 】✔ El taladro atornillador eléctrico proporciona al usuario un cómodo, suave y equilibrado agarre. ✔ La luz LED ayuda a perforar y atornillar en lugares oscuros ✔ El interruptor giratorio le permite rotar hacia adelante o hacia atrás según sus necesidades ✔ Bloqueo automático del portabrocas de 0,8-10mm para brocas de cambio rápido.',
        '【 Ideas regalo y agradable regalo 】x1 GOXAWEE Taladro Atornillador, x2 Batería recargable, x1 Cargador rápido, x1 Eje flexible (250mm), x9 Llaves de tubo, x6 Puntas de destornillador, x1 Adaptador hexagonal, x1 Soporte de extensión hexagonal, x3 Brocas para madera, x3 Brocas para metal, x1 Broca de carburo, x72 Accesorios de fijación y x1 Caja de herramientas.',
      ],
    },
    {
      name: 'Taladro Atornillador 21V, TEENO 41Pcs Kit Destornillador Eléctrico (2 Baterías de Litio 1500mAh, 40N.m Par Máx, 2 Velocidades, 10mm Portabrocas Automatico)',
      category: 'Taladros Atornilladores',
      slug: 'Taladro-Atornillador-21V-TEENO',
      image: '/images/taladrosAtornillador/61cfqqH5u7S._AC_SL1000_.jpg',
      price: 61.99,
      brand: '	TEENO',
      rating: 4.1,
      numReviews: 1258,
      countInStock: 0,
      description: [
        'Taladro sin cuerda Componente del paquete: 1 * taladro sin cable + 1 * Caso plástico + 1 * Guantes profesionales + + 35 * Accesorios + 1 * Universal Head + 1 * Cargador + 2 * Baterías',
        'Tipo de fuente de alimentación: Batería',
        'Batería: 2 baterías de iones de litio 21V',
        'Tipo del tirador: 10m m Automático',
      ],
    },
    {
      name: 'BLACK+DECKER BCF611CK-QW - Atornillador a batería 3.6V(1.5Ah) litio, 5.5Nm, de carga rápida',
      category: 'Taladros Atornilladores',
      slug: 'BLACK+DECKER-BCF611CK-QW -Atornillador',
      image: '/images/taladrosAtornillador/71ITLPRvwyL._AC_SL1500_.jpg',
      price: 24.49,
      brand: 'Black+Decker',
      rating: 4.4,
      numReviews: 1485,
      countInStock: 19,
      description: [
        ' Atornillador con batería de litio integrada de 3.6v(1.5ah) y de carga rápida en menos de 1 hora con puerto de carga micro usb.',
        ' Par de apriete de 5.5nm, velocidad de 180 rpm y porta-puntas de 1/4” hexagonal que permite un cambio fácil y rápido de los accesorios.',
        ' Probado: 100 tornillos con una carga de 15 minutos y hasta 500 tornillos con una carga de 60 minutos (resultados obtenidos con tornillos 3.5 x 25mm en madera de pino de 408mm con agujero guía pre-establecido).',
        ' Función reversible, modo linterna y diseño ultra compacto que ofrecen comodidad y eficiencia mientras esta funcionando.',
        ' Incluye: 10 puntas para atornillar, cargador rápido de 2ah y estuche de almacenamiento.',
      ],
    },

    {
      name: 'Black+Decker BEG010-QS - Amoladora 115mm, 710W, 12.000 rpm',
      category: 'Amoladoras',
      slug: 'Black+Decker-BEG010-QS-Amoladora',
      image: '/images/amoladoras/81M6s7FW1uL._AC_SL1500_.jpg',
      price: 25.3,
      brand: 'Black+Decker',
      rating: 4.5,
      numReviews: 2359,
      countInStock: 36,
      description: [
        'Radial de 115 mm con potente motor de 710w',
        'Facilita el corte de tubos metálicos, losas de piedra y baldosas de cerámica, así como la eliminación de óxido y pintura',
        'Motor de 12.000 rpm con protección contra re-arranque para mayor seguridad mientras opera',
        'Mango ajustable en dos posiciones para mayor versatilidad mientras trabajas',
        'El diámetro compacto de esta amoladora con cable permite un agarre cómodo y le permite acceder a áreas difíciles',
      ],
    },
    {
      name: 'Bosch Professional GWS 7-115 E - Amoladora angular (720 W, 2800 – 11000 rpm, Ø Disco 115 mm, protección rearranque, en caja)',
      category: 'Amoladoras',
      slug: 'Bosch-Professional-GWS-7-115-E-Amoladora-angular',
      image: '/images/amoladoras/81HD9lo7FrL._AC_SL1500_.jpg',
      price: 56.88,
      brand: 'Bosch',
      rating: 4.7,
      numReviews: 13188,
      countInStock: 4,
      description: [
        'Incluye miniamoladora gws 7-115 e, cubierta protectora, brida de fijación, empuñadura adicional, llave de dos agujeros, tuerca tensora',
        'Perímetro de empuñadura reducido con 720 w de potencía',
        'Perímetro de empuñadura reducido (176 mm), comparado con otras amoladoras angulares de la misma categoría de potencía, que proporciona una gran comodidad en el trabajo',
        'Motor de 720 w de potencía con un peso de solo 1, 9 kg, para trabajar durante periodos prolongados',
        'Cabezal plano para que el trabajo resulte cómodo incluso en zonas estrechas',
        'Protección contra rearranque evita la puesta en marcha automática de la herramienta tras una interrupción de corriente',
        'Preselección del número de revoluciones en 6 niveles para trabajar con diferentes materiales',
      ],
    },
    {
      name: 'Einhell 4430619 TC-AG 125 - Amoladora Angular, Diámetro de 125 mm, sin Disco de Corte, 850 W, 230 V, color Rojo/Negro',
      category: 'Amoladoras',
      slug: 'Einhell-4430619-TC-AG-125-Amoladora-Angular',
      image: '/images/amoladoras/51lNAaPVRIL._AC_SL1464_.jpg',
      price: 28.9,
      brand: 'Einhell',
      rating: 4.4,
      numReviews: 2092,
      countInStock: 50,
      description: [
        'Carcasa de plástico ergonómica con robusto cabezal de engranaje plano de aluminio',
        'Gran potencia de 850 W con velocidad de giro constante de 12.000 revoluciones por minuto',
        'Asidero adicional montable en 2 posiciones para cada tarea',
        'Práctico bloqueo de husillo para el cambio de herramienta rápido',
        'Incluida llave de gancho para el cómodo cambio de herramienta',
        'Suministro de red de 230 V | 50 HZ',
        'Peso bruto del producto sin embalaje de 2,3 Kg',
      ],
    },
    {
      name: 'Bosch PWS 700-115 - Amoladora (700 W, Ø115 mm, maletín)',
      category: 'Amoladoras',
      slug: 'Bosch-PWS-700-115-Amoladora',
      image: '/images/amoladoras/51ls7S9PczL._AC_SL1009_.jpg',
      price: 45.01,
      brand: 'Bosch Home and Garden',
      rating: 4.6,
      numReviews: 714,
      countInStock: 13,
      description: [
        'Incluye: Miniamoladora PWS 700-115, cubierta protectora de ajuste rápido, empuñadura y maletín de transporte',
        'Miniamoladora PWS 700-115 - La potencia segura en la empuñadura',
        'Diseño compacto y peso reducido para un manejo siempre seguro y controlado',
        'Extremadamente versátil para tronzar, cortar, lijar y cepillar metales, azulejos y piedras de hormigón',
        'Flexible y segura gracias al ajuste de la cubierta protectora sin herramientas y la codificación de la cubierta protectora para evitar un montaje incorrecto',
        'Más confort gracias a la opción de montaje por ambos lados de la empuñadura',
        'Rendimiento óptimo y vida útil más larga gracias al sistema de protección de sellado patentado por Bosch; evita la acumulación de polvo de lijado o de tronzado en el rodamiento de bolas',
      ],
    },
    {
      name: 'Bosch Professional GWS 20-230 JH - Amoladora angular (2000 W, disco Ø 230 mm, arranque suave, en caja)',
      category: 'Amoladoras',
      slug: 'Bosch-Professional-GWS-20-230-JH-Amoladora-angular',
      image: '/images/amoladoras/51RJ5FBT7FS._AC_SL1200_.jpg',
      price: 118.07,
      brand: 'Bosch Professional',
      rating: 4.6,
      numReviews: 166,
      countInStock: 24,
      description: [
        'Amoladora eficiente de la clase de 2.000 vatios para una amplia gama de aplicaciones de corte y amolado',
        'El motor de 2.000 vatios proporciona excelentes resultados para el trabajo en general',
        'La protección contra el reinicio y el arranque suave aumentan la protección del usuario',
        'La forma compacta y ergonómica de la carcasa garantiza un fácil manejo para una amplia gama de aplicaciones',
        'Volumen de suministro: GWS 20-230 JH, mango adicional, en caja de cartón',
      ],
    },

    {
      name: 'BLACK+DECKER Lijadora de Detalle Mouse 55W 11.000RPM Diametro Orbita 1.5mm Incluye 15 Accesorios y Bolsa de Transporte BEW230BC-QS',
      category: 'Lijadoras',
      slug: 'BLACK+DECKER-Lijadora-de-Detalle-Mouse',
      image: '/images/lijadoras/71rSLwgwSgL._AC_SL1500_.jpg',
      price: 22.54,
      brand: 'Black+Decker',
      rating: 4.5,
      numReviews: 3614,
      countInStock: 28,
      description: [
        'Lijadora orbital de detalles 55W adecuada para pintar, barnizar, eliminar óxido y lijar en espacios reducidos',
        'Diámetro de órbita 1.5mm y tamaño de hoja 110mm/cm2',
        'Velocidad de 11.000 rpm entrega un rendimiento óptimo para aplicaciones de detalle',
        'Cuenta con adaptador de aspirador para mantener el área de trabajo limpia',
        'Incluye: 15 accesorios lijar y bolsa de transporte',
      ],
    },
    {
      name: 'Bosch PSM 100 A - Multilijadora, 3 hojas de lija K 80/ K 120/ K 160, maletín (100 W, nº de carreras en vacío: 26.000 opm, Ø circuito oscilante: 1,4 mm)',
      category: 'Lijadoras',
      slug: 'Bosch-PSM-100-A-Multilijadora',
      image: '/images/lijadoras/81r-zQLJMOL._AC_SL1500_.jpg',
      price: 48.99,
      brand: 'Bosch Home and Garden',
      rating: 4.6,
      numReviews: 1289,
      countInStock: 3,
      description: [
        'Incluye: Multilijadora PSM 100 A, 3 hojas de lija K 80/ K 120/ K 160, maletín',
        'PSM 100 A: la lijadora multitalento de fácil manejo',
        'Ligera y compacta, perfecta para lijar en zonas de difícil acceso, así como en superficies pequeñas y medianas',
        'Trabajo limpio gracias al sistema microfiltro: el elemento de aspiración integrado aspira el polvo directamente al interior del depósito del sistema microfiltro suministrado',
        'Cierre de cardillo para el cambio rápido de la hoja de lija',
        'Placa lijadora dividida en dos: para el aprovechamiento óptimo de la hoja de lija, la punta delta de la hoja y de la placa pueden soltarse y girarse sin esfuerzos',
        'Conexión para aspiración de polvo para aspiradores universales',
      ],
    },
    {
      name: 'Lijadora Eléctrica 220W - JELLAS Máquina Lijadora Compacta para Madera, 13000 RPM con Recolección de Polvo, 16 Piezas de Papel de Lija, Lija de Dedo y Almohadilla de Lijado Incluidos, MS220',
      category: 'Lijadoras',
      slug: 'Lijadora-Eléctrica-220W-JELLAS',
      image: '/images/lijadoras/71UQ2FaB76L._AC_SL1500_.jpg',
      price: 36.99,
      brand: 'Jellas',
      rating: 4.2,
      numReviews: 433,
      countInStock: 3,
      description: [
        '[Motor de 220W / 13000 RPM] El motor de cobre puro con potencia de 220W y velocidad 13000 revoluciones por minuto, se puede usar de manera más agresiva para sacar más material de la superficie más rápido y también se puede usar en materiales más duros de manera más efectiva. Tamaño de la almohadilla de lijado 148X148X98mm con un diámetro de péndulo de trabajo de 1.6mm que reduce efectivamente el tiempo de trabajo en comparación con otras lijadoras de baja potencia, indica mejor calidad y experie',
        '[Eficiente recogida de polvo] Para otros sistemas de recogida de polvo tienen que usar una manguera de vacío conectada, que es difícil de manejar. En cambio, la lijadora de Jellas viene con una caja de polvo cuando está subido en una escalera y / o trabajando por encima de la altura de los hombros, no es necesario arrastrar a lo largo de una manguera de vacío al utilizar una lijadora eléctrica',
        '[Diseño ergonómico] El mango completamente cubierto de caucho es ergonómico, proporciona un buen agarre y reduce la fatiga; la vibración de la lijadora puede generar un nivel de ruido tan bajo como 75db; y el cable de alimentación de 3 m permite trabajar mucho tiempo y con menos limitaciónes. Extensión de lijadora de dedos integrada adicional que facilita el lijado en lugares difíciles de alcanzar',
        '[16 piezas de papel de lija] Con papel de lija estándar de 12 piezas (4 piezas * P80 y 4 piezas * P120 y 4 piezas * P240) y papel de lija de 4 piezas (2 piezas * P80 y 1 piezas * P120 y 1 piezas * P240) pueden cumplir diferentes aplicaciones. Y el diseño de velcro te permite cambiar el papel de lija rápidamente',
        '[El paquete incluye] 1 x lijadora de ratón para detalles, 1 x placa base de lijado para detalles, 1 x accesorio para lija de dedo, 12 x papel de lija con detalles estándar, 4 x papel de lija para dedo, 1 x caja de polvo, 1 x manual de usuario',
      ],
    },
    {
      name: 'Lijadora Eléctrica 200W Tilswall, 15000RPM Lijadora de Detalles Mouse de Diámetro Orbital 1,6mm, con 12 Piezas Lijas de 60 grano y de 120 grano para Alisar Madera y Quitar Pintura',
      category: 'Lijadoras',
      slug: 'Lijadora-Eléctrica-200W-Tilswall',
      image: '/images/lijadoras/71xGEsZulBL._AC_SL1500_.jpg',
      price: 34.99,
      brand: 'Tilswall',
      rating: 4.3,
      numReviews: 1458,
      countInStock: 1,
      description: [
        '【Alto Rendimiento】: Nuestra lijadora de acabado tiene un motor de cobre fino de 200 W con baja resistencia, que ofrece un rendimiento de 15000 RPM. La órbita excéntrica más alta (diámetro de 1,6 mm) es más uniforme e ideal para lijar, pulir las superficies pequeñas y reparar pintura',
        '【Caja de Polvo】: Nuestra lijadora es diseñada con una gran caja reutilizable para recoger el polvo, proporcionándole un entorno de trabajo limpio. El diseño compacto se fija de forma segura en la máquina para evitar que la caja se caiga durante el uso, brindando más conveniencia para usted.',
        '【Interruptor de Polvo & Enfriamiento】: El interruptor a prueba de polvo evita que las virutas de madera entran en la máquina de lijar madera, mantenióndolo limpio y extendiendo su vida útil. Además, la lijadora está equipado con una fuerte disipación de calor, permite que la máquina funcione eficientemente sin quemar y dañar',
        '【Uso Cómodo】: La lijadora de detalles de 1.15 kg es ligero, su mango de goma suave puede reducir efectivamente las vibraciones durante el uso. Además, el diseño ovalado brinda a su mano un mejor agarre y control, evitando la fatiga. Muy adecuado para pulir madera, pintura y muebles,etc.',
        '【Paquete Incluido】: Nuestro paquete se viene con 1 x lijadora para madera Tilswall, 12 x lijas abrasivas (6 piezas x 80 grano abrasivo,6 piezas x 120 granos abrasivos), 1 x Manual en español. Si tiene algún problema en 28 meses, contáctenos. No se preocupe, estamos siempre a su servicio',
      ],
    },
    {
      name: 'Lijadora Orbital 300W, HYCHIKA Lijadora Eléctrica con Motor de Cobre Puro, 6 Velocidad, 13000RPM, 12PCS Lija de 125mm (240/120/80 Grano), con Bolsillo Lavable de Recogida, para Lijar Madera y Metal',
      category: 'Lijadoras',
      slug: 'Lijadora-Orbital-300W-HYCHIKA',
      image: '/images/lijadoras/81hz0B-fX9S._AC_SL1500_.jpg',
      price: 36.99,
      brand: 'HYCHIKA BETTER TOOLS FOR BETTER LIFE',
      rating: 4.3,
      numReviews: 249,
      countInStock: 0,
      description: [
        '【6 VELOCIDADES】 Lijadora Orbital con motor de cobre puro, tiene un botón para ajustar 6 velocidad ajustable. Esto le permite elegir la velocidad de Lijadora Orbital Electrica más adecuada para el trabajo. Velocidad entre 6000 y 13000RPM, Potencia: 300W, puede mejorar la eficiencia. Lijas gruesas se giran a alta velocidad para un pulido áspero y el finas para un pulido fino.',
        '【12PCS Lijas】 Lijadora Orbital está equipada con 12 Lijas de Lijadora de malla de 80, 120, 240 granos, que pueden usarlos para pulir materiales de madera y metal. Diámetro de lijadora es 125mm, Es fácil de encontrar y comprar lijas en Amazon.',
        '【BASE GIRATORIA 360 °】 Base de lijado giratoria de 360 ° asegura que la superficie de lijado queda lisa sin trazas. Cambia rápidamente las lijas para mejorar en gran medido la eficiencia del trabajo.',
        '【RECOGIDA DE POLVO】 Lijadora Electrica está diseñada con 8 orificios de recolección de polvo, combinado con un sistema de recolección de polvo y una caja de recolección. La eficiencia es mayor, lo que puede trabajar en un ambiente más limpio y cómodo. Es muy fácil de instalar esta caja y quitarla. Se puede limpiarla con agua. Hay un anillo de goma en la boca de la bolsa de la aspiradora, que hace que esté bien conectada, y las astillas no se dispersan fácilmente.',
        '【TRABAJO EFICIENTE Y CÓMODO】 Está cubierta con goma, y tiene varias formas de agarre. Es muy fácil de operar esta Lijadora Orbital Electrica con una sola mano y mejora la comodidad y el control del operador.',
      ],
    },

    {
      name: 'Dremel Versatip 2000 - Pirograbador a gas butano con 6 puntas para soldadura, pirografo, fusión, corte en caliente, compresión (duración de encendido máximo 90 min)',
      category: 'Soldadores',
      slug: 'Dremel-Versatip-2000-Pirograbador-a-gas-butano',
      image: '/images/soldadores/61lpNdFHpdL._SL1500_.jpg',
      price: 44.0,
      brand: 'Dremel',
      rating: 4.5,
      numReviews: 8441,
      countInStock: 13,
      description: [
        'Incluye: Versatip, cabezal con soplador de aire caliente, cabezal de llama ancha/plana, caja metálica de almacenaje, cuchilla de corte, cuchilla para corte en caliente, esponja para soldadura, estuche, estaño para soldar, punta de soldadura y reflector',
        'Una herramienta para 6 aplicaciones diferentes: soldadura, fusión, corte en caliente, compresión, grabado a fuego (pirograbado) y eliminación de pintura',
        'Siempre lista para usar',
        'Se puede utilizar en cualquier momento y en cualquier parte',
        'Permite realizar tareas complejas y minuciosas',
      ],
    },
    {
      name: 'E·Durable Soldadores de Estaño Electronica, 60W 220V Kit del Soldador 5pcs Puntas Diferentes,Alambre de Soldadura Soporte,Cortador,Pinzas,destornillador',
      category: 'Soldadores',
      slug: 'E·Durable-Soldadores-de-Estaño-Electronica-60W-220V',
      image: '/images/soldadores/61sONbaNn2L._AC_SL1000_.jpg',
      price: 13.99,
      brand: 'E·Durable',
      rating: 4.3,
      numReviews: 449,
      countInStock: 3,
      description: [
        ' Kits de soldadura ampliamente utilizados: las herramientas de soldadura de soldador se usan ampliamente para soldar placas de circuito, reparación de electrodomésticos, aficionados al bricolaje en el hogar, soldadura de joyas. La mejor opción para principiantes en soldadura',
        ' Excelente pistola de soldadura: no necesita estación de soldadura, solo conéctelo y juegue. Fácil de operar Ajuste la temperatura de acuerdo a sus necesidades con la rueda de perilla del soldador electrónico.',
        ' 5 puntas de hierro: cinco puntas diferentes hacen que el soldador sea fácil de colocar para guitarra, computadoras, hardware y condensadores o accesorios de TV, etc.',
        ' Más Accesorios：este destornillador mini pluma incluye 2 brocas de destornillador de dos puntas que funciona muy bien para el iPhone 7/7Plus, iPhoneX, iPhone Plus 8/8, P 6/6/6/5/5 / 5C/4S/4/SE, iPod, iWatch, este kit de reparación de iphone incluyen Y000 triwing destornillador Pentalobe p2 destornillador, ph0000 destornillador phillips y 2,0 mm cabeza plana Destornillador bit set',
        ' Kit de soldadura de hierro Soldering de hierro incluyen: soldador, para bomba, 5pcs diferentes puntas, pinzas, soldadura de tubo, soporte, alambre de corte diagonal, herramientas de palanca de doble cabezal plástico verde es mejor para el uso de vario reparado diyer',
      ],
    },
    {
      name: 'Soldadores de Estaño Electronica, SREMTCH [Nuevo Diseño] 60W Kit del Soldador de 220 ℃ a 480℃ Temperatura Ajustable con Interruptor 5pcs Puntas Diferentes, Soporte, Alambre de Soldadura',
      category: 'Soldadores',
      slug: 'Soldadores-de-Estaño-Electronica-SREMTCH-60W',
      image: '/images/soldadores/61NuI9ARmVL._AC_SL1500_.jpg',
      price: 14.99,
      brand: 'SREMTCH',
      rating: 4.3,
      numReviews: 331,
      countInStock: 0,
      description: [
        'Fácil de Usar: Temperatura de los SREMTCH soldadores de estaño se puede ajustar entre los 200 y los 480 grados y la luz indicadora muestra el estado de trabajo; Es muy fácil y conveniente para usar',
        'Tecnología Avanzada para Calefacción y Refrigeración: Las herramientas de estaño SREMTCH son una opción que se calienta mediante la tecnología de inducción de cerámica interior climatizada en poco tiempo en 30 segundos',
        'Disipación de Calor Eficiente: Diseño de tubos de acero ayuda a enfriar rápidamente. Los cuatro orificios de ventilación en la punta de soldadura ofrecen mejor disipación de calor que otras. PCBA mejorada con resistencia fija de viruta también ayuda a disipar el calor rápidamente',
        'Nuevo Diseño de Interruptor: Added más un interruptor, puede activarlo de encendido/apagado fácilmente para ahorrar energía y garantizar la seguridad de soldadura. Indicador será una buena pista para evitar que se queme por accidental',
        'Más Accesorios: Vienen con 5 puntas intercambiables; Soporte para soldadores; Alambre de Soldadura',
      ],
    },
    {
      name: 'ROTHENBERGER 1500000447 - Socket welder eco 20, 25 y 32 mm',
      category: 'Soldadores',
      slug: 'ROTHENBERGER-1500000447-Socket-welder-eco',
      image: '/images/soldadores/71RjtPIhWRL._SL1500_.jpg',
      price: 98.45,
      brand: 'ROTHENBERGER',
      rating: 4.1,
      numReviews: 24,
      countInStock: 0,
      description: [
        'Soldador de tubería con 800 W.',
        'Para soldar tuberías y manguitos de PP, PP, PE y PVDF.',
        '260 ° C. ',
      ],
    },
    {
      name: 'Soldadora MIG 100 Sin gas en Rebaja',
      category: 'Soldadores',
      slug: 'Soldadora-MIG-100-Sin-gas-CE-GSH',
      image: '/images/soldadores/7180z6pk-hL._AC_SL1500_.jpg',
      price: 99.99,
      brand: 'CE-GSH',
      rating: 4.1,
      numReviews: 19,
      countInStock: 1,
      description: [
        'Tensión De Red Monofásica. Volt 220. Frecuencia HZ 50. Fusible Max Amp 13. Tensión Max En Vacio Volt 19,5. Intervalo de corriente de trabajo 50-90 A. Ideal para soldar chapa 0-3mm. Portatil. Protección de sobrecarga, Mini carrete de alambre de 0. 9 mm, careta anti proyecciones con cristal negro, cepillo con piqueta.',
        'Control de velocidad de giro de carrete. Control de potencia. Rendimiento 10% A 35% A 60% A 110 A 60 A 35 A Ventilada. Si Hilos ø mm 0,9 y también 0,6. Clase De Aislamiento H. Clase De Protección IP 21',
        'Dimensiones (LxAxA) cm 36x20x32. Peso con accesorios 14KG. Hilo de soldadura tipo: recubierto de fundente. Ventilador de enfriamiento. Control de velocidad de giro de carrete. Modo de transporte: ASA superior. Accesorios incluidos',
        'Este soldador dispone de 4 niveles depotencia, regulados mediante los botones min/max y 1/2, de menos potencia a mayor seria: min/1, min/2, max/1 y max/2. este soldador esta recomendado para chapas de 1mm a 3mm,',
      ],
    },

    {
      name: 'Stanley DN200/8/6 - Compresor de aire',
      category: 'Compresores de aire',
      slug: 'Stanley-DN200/8/6-Compresor-de-aire',
      image: '/images/compresoresAire/71KbeNPd9rS._AC_SL1500_.jpg',
      price: 76.55,
      brand: 'Stanley',
      rating: 4.4,
      numReviews: 833,
      countInStock: 37,
      description: [
        'Compresor de pistón, 8 bar de presión',
        'De facil uso gracias al encendido on/off en el panel de control con manometro de rapida lectura',
        'Dotado de gancho para colgar accesorios',
        'Grifo de purga de esfera, profesional, con paso aumentado para evitar obstrucciones y bloqueo',
        'Aire aspirado (lts/min): 180',
      ],
    },
    {
      name: 'MICHELIN 009526 Verificador de Presión Digital Y Desgaste Neumáticos, AUTOMOVIL',
      category: 'Compresores de aire',
      slug: 'MICHELIN-009526-Verificador-de-Presión-Digital-Y-Desgaste-Neumáticos',
      image: '/images/compresoresAire/71XCj0XAA9L._AC_SL1500_.jpg',
      price: 17.4,
      brand: 'MICHELIN',
      rating: 4.4,
      numReviews: 725,
      countInStock: 0,
      description: [
        'Controlador de presión de nueva generación + medición de profundidad del neumático',
        'Visualización de la presión de los neumáticos en bar (0,35-> 7bar) con una precisión de lectura de 0,05 bar',
        'Visualización de profundidad de las ranuras de los neumáticos en mm',
        'Baterías suministradas (batería cr 2032 x 1)',
        'Estilo: Universal',
      ],
    },
    {
      name: 'Einhell TC-AC 190/24 - Compresor, depósito de 24 l, 2850 rpm, 8 bar, 1500 W, 220 V, color rojo y negro (ref. 4007325) & Kit de accesorios para compresor de aire, 5 unidades (ref.4132720)',
      category: 'Compresores de aire',
      slug: 'Einhell-TC-AC-190/24-Compresor',
      image: '/images/compresoresAire/51DMrBBmeKL._AC_SL1001_.jpg',
      price: 130.9,
      brand: 'Einhell',
      rating: 4.3,
      numReviews: 310,
      countInStock: 11,
      description: [
        'Lubricación por aceite asegura una larga vida útil',
        'Control de nivel de aceite a través de pequeña ventana de inspección',
        'El depósito de 50l ofrece reservas de aire suficientes',
        'Muchas aplicaciones hasta 10 bares ajustables mediante reductores de presión',
        'Pistola de pulverización para pintura con vaso de gravedad',
        'Pistola de aire comprimido que se puede utilizar como dispositivo de soplado y pistola con ventosa',
        'Inflador de neumáticos con manómetro',
        'Manguera de aire en espiral de 4 m',
      ],
    },
    {
      name: 'MICHELIN 9519 Compresor de aire portatil programable, 12 V',
      category: 'Compresores de aire',
      slug: 'MICHELIN-9519-Compresor-de-aire-portatil-programable-12-V',
      image: '/images/compresoresAire/51f1fkUfI+L._AC_SL1009_.jpg',
      price: 48.55,
      brand: 'MICHELIN',
      rating: 4.4,
      numReviews: 3966,
      countInStock: 1,
      description: [
        'Compresor digital 12 V/ programable. Inflado de un neumático estándar en 3 minutos',
        'Permite inflar desde 0.05 bar hasta 7 bar. Conexión a la toma del encendedor 12 V. Ideal para automóviles, motos, bicicletas, actividades de ocio (globos, colchones de aire)',
        'Función predeterminada: le permite inflar automáticamente hasta la presión seleccionada en la pantalla digital. El compresor se detiene una vez que se alcanza la presión deseada. Pantalla digital retroiluminada para leer y seleccionar la presión deseada',
        'Lámpara de iluminación LED. Toma de 12 V y USB para alimentar apartos electrónicos. Almacenaje para la manguera de inflado. Manguera de nylon de 60 cm',
        'Punta de latón para un sellado perfecto en la válvula del Neumático. Se suministra con puntas para inflar neumáticos de bicicleta, globos y juguetes inflables. Almacenamiento de las puntas en la parte posterior del compresor. Presión de aire: 16 l/min. Ruidos y vibraciones mínimas',
      ],
    },
    {
      name: 'Black+Decker ASI300-QS - Compresor de aire, 160 PSI, 11 bar, Fuente de alimentación: Cable eléctrico, Rojo/Negro',
      category: 'Compresores de aire',
      slug: 'Black+Decker-ASI300-QS-Compresor-de-aire',
      image: '/images/compresoresAire/71IsdA+JxKL._AC_SL1500_.jpg',
      price: 97.14,
      brand: 'Black+Decker',
      rating: 4.2,
      numReviews: 4504,
      countInStock: 1,
      description: [
        'Compresor de aire de 160 PSI con mucha potencia, responde a las tareas de inflado más frecuentes como inflado de ruedas de bicicletas, motos, neumáticos grandes y equipamiento de deporte como balones',
        'El compresor de aire puede ser utilizado en casa con electricidad (CA) o en vehículos (CC)',
        'Sencilla rueda de selección de presión que ajusta de manera precisa la presión deseada para realizar la tarea de trabajo',
        'Su diseño compacto permite guardarlo fácilmente en el maletero del coche/ estantería/ armario',
        'Incluye: 18 metros de cable CC, 31 metros de cable 12V (CA), 3 accesorios para equipamiento de deporte y manguera con accesorios para neumáticos de coche',
      ],
    },

    {
      name: 'Einhell 2260112 Carretilla de Mano',
      category: 'Carretillas',
      slug: 'Einhell-2260112-Carretilla-de-Mano',
      image: '/images/carretillas/71GEg+AaGaL._SL1500_.jpg',
      price: 726.88,
      brand: 'Einhell',
      rating: 4.4,
      numReviews: 7490,
      countInStock: 37,
      description: [
        'Cerradura para extender la manija',
        'Estructura de aluminio',
        'Cuchilla de apoyo plegable',
        'Ruedas de goma con casquillo metálico',
        'Capacidad máxima de carga 90 kg.',
      ],
    },
    {
      name: 'Stanley SXWTD-FT582 Carretilla Plegable, Amarillo/Negro',
      category: 'Carretillas',
      slug: 'Stanley-SXWTD-FT582-Carretilla-Plegable',
      image: '/images/carretillas/61LPr06jH9L._AC_SL1000_.jpg',
      price: 50.42,
      brand: 'Stanley',
      rating: 4.4,
      numReviews: 3069,
      countInStock: 0,
      description: [
        'Capacidad 90 kg',
        'Mango de pp ajustable en altura',
        'Para abrir y cerrar En segundos',
        'Robusto pero ligero y compacto',
      ],
    },
    {
      name: 'Hivexagon Carrito de Equipaje Plegable, Compacto Ligero Duradero de Aluminio Capacidad de Carga de 40kg/88lbs para Equipaje, Viajes, de compras, Uso en Oficina y Transporte HG405',
      category: 'Carretillas',
      slug: 'Hivexagon-Carrito-de-Equipaje-Plegable',
      image: '/images/carretillas/618lpV9TV8L._SL1001_.jpg',
      price: 26.99,
      brand: 'Hivexagon',
      rating: 4.1,
      numReviews: 220,
      countInStock: 0,
      description: [
        'Dimensiones del cuerpo: 15.7" x 10.6" x 3.5"/40 x 27 x 9cm, Peso: 2.75 libras. / 1.25kg. Plegable para transportarlo y guardarlo fácilmente.',
        'Estructura de altura ajustable para 3 tamaños: 40cm/15.7”, 60cm/23.6”, 95cm/37.4”.Compatible con productos de diferentes tallas',
        'Incluye 2 cuerdas elásticas con gancho para fijar y proteger el equipaje',
        'Construido con aluminio sólido y ligero, anti corrosivo y anti oxidable. Ruedas de mayor tamaño (8cm de diámetro) para mejorar su manejo.',
        'Construcción resistente y ligera, se abre y se cierra en cuestión de segundos con un manejo sencillo.',
      ],
    },
    {
      name: 'ATHLON TOOLS Carretilla plegable de aluminio | zona de carga con almohadillas antideslizantes | ruedas con bandas de rodadura suaves | incl. 2 cuerdas extensibles',
      category: 'Carretillas',
      slug: 'ATHLON-TOOLS-Carretilla-plegable-de-aluminio',
      image: '/images/carretillas/71sUmgjClRL._AC_SL1500_.jpg',
      price: 49.9,
      brand: 'ATHLON TOOLS',
      rating: 4.5,
      numReviews: 1693,
      countInStock: 0,
      description: [
        ' 𝗜𝗗𝗘𝗔𝗟 𝗣𝗔𝗥𝗔 𝗧𝗥𝗔𝗡𝗦𝗣𝗢𝗥𝗧𝗔𝗥 𝗖𝗔𝗥𝗚𝗔𝗦 𝗦𝗜𝗡 𝗘𝗦𝗙𝗨𝗘𝗥𝗭𝗢: La carretilla es perfecta para todas las tareas de transporte relacionadas con las compras, el hogar o el jardín.',
        ' 𝗘𝗦𝗧𝗔𝗕𝗟𝗘 𝗬 𝗟𝗜𝗚𝗘𝗥𝗔: Todas las piezas de transporte son de aluminio robusto. La capacidad de carga máxima es de 70 kg. ¡Tan solo pesa 3,2 kg! La zona de carga mide 39 x 28 cm.',
        ' 𝗦𝗨𝗔𝗩𝗘𝗦 𝗬 𝗕𝗜𝗘𝗡 𝗣𝗘𝗡𝗦𝗔𝗗𝗔𝗦: Las ruedas y las suspensiones de las ruedas están completamente montadas con rodamientos de bolas y, por lo tanto, son especialmente suaves y duraderas. Las bandas de rodadura suaves y grises de las ruedas giran silenciosamente y no marcan las superficies.',
        ' 𝗖𝗢𝗠𝗣𝗔𝗖𝗧𝗔 𝗬 𝗗𝗘 𝗗𝗜𝗠𝗘𝗡𝗦𝗜𝗢𝗡𝗘𝗦 𝗥𝗘𝗗𝗨𝗖𝗜𝗗𝗔𝗦: La carretilla puede desplegarse y plegarse en cuestión de segundos. Cabe en cada maletero, cobertizo de jardín y trastero. El asa telescópica extra larga (110cm) cuenta con un ajuste rápido y las ruedas se pliegan y se despliegan automáticamente junto con la zona de carga.',
        ' 𝗤𝗨É 𝗩𝗜𝗘𝗡𝗘 𝗜𝗡𝗖𝗟𝗨𝗜𝗗𝗢: Una carretilla de aluminio completamente montada, dos cuerdas extensibles para asegurar la carga, una factura digital y un servicio de atención al cliente atento y servicial.',
      ],
    },
    {
      name: 'ATHLON TOOLS Carretilla plegable de aluminio para cargas pesadas | Grandes ruedas de marcha suave con bandas de rodadura blandas | Incluye 2 cuerdas extensoras',
      category: 'Carretillas',
      slug: 'ATHLON-TOOLS-Carretilla-plegable-de-aluminio-para-cargas-pesadas',
      image: '/images/carretillas/71MFq3EoJJL._AC_SL1500_.jpg',
      price: 79.9,
      brand: 'ATHLON TOOLS',
      rating: 4.5,
      numReviews: 629,
      countInStock: 0,
      description: [
        ' Ó𝗣𝗧𝗜𝗠𝗔 𝗣𝗔𝗥𝗔 𝗘𝗟 𝗧𝗥𝗔𝗡𝗦𝗣𝗢𝗥𝗧𝗘 𝗗𝗘 𝗖𝗔𝗥𝗚𝗔𝗦 𝗦𝗜𝗡 𝗘𝗦𝗙𝗨𝗘𝗥𝗭𝗢𝗦: La carretilla para cargas pesadas es ideal para usar en todas las tareas de transporte como compras, labores del hogar o del jardín.',
        ' 𝗘𝗦𝗧𝗔𝗕𝗟𝗘 𝗬 𝗟𝗜𝗚𝗘𝗥𝗔: Las suspensiones de las ruedas, el marco, el mango telescópico y la superficie de carga son de aluminio robusto. La capacidad de carga máxima es de 150 kg, ¡con un peso propio de solo 5,9 kg! La pala de carga tiene un área extra grande de 48 x 34 cm.',
        ' 𝗗𝗘 𝗠𝗔𝗥𝗖𝗛𝗔 𝗦𝗨𝗔𝗩𝗘 𝗬 𝗕𝗜𝗘𝗡 𝗖𝗢𝗡𝗖𝗘𝗕𝗜𝗗𝗔: Las ruedas tienen rodamientos de bolas y, por lo tanto, son especialmente suaves y duraderas. Las suaves bandas de rodadura grises de las ruedas son silenciosas y no dejan marcas de desgaste.',
        ' 𝗖𝗢𝗠𝗣𝗔𝗖𝗧𝗔 𝗬 𝗔𝗛𝗢𝗥𝗥𝗔 𝗘𝗦𝗣𝗔𝗖𝗜𝗢: La carretilla se puede abrir y cerrar en cuestión segundos. Cabe en todos los maleteros, en todas las casetas de jardín y en todos los cuartos trasteros. El mango telescópico extra largo (115 cm) tiene un ajuste rápido y las ruedas se pliegan y despliegan automáticamente junto con la superficie de carga.',
        ' L𝗢 𝗤𝗨𝗘 𝗨𝗦𝗧𝗘𝗗 𝗥𝗘𝗖𝗜𝗕𝗘: Una carretilla de aluminio para cargas pesadas completamente ensamblada, dos cuerdas extensoras para asegurar la carga, una factura digital y un servicio de atención al cliente amable y competente.',
      ],
    },

    {
      name: 'Transpaleta Manual 2500 kg, Horquillas 1150x525 mm, Ruedas Poliuretano/Rodillos Nylon',
      category: 'Transpaletas',
      slug: 'Transpaleta-Manual-2500 kg',
      image: '/images/transpaletas/31IIr8eqWPS.jpg',
      price: 329.0,
      brand: 'Pramac',
      rating: 5.0,
      numReviews: 1,
      countInStock: 1,
      description: [
        'Ruedas de poliuretano',
        '2500kg de capacidad de carga',
        'Horquillas: 1150x525mm',
        'Rodillos Dobles de nylon',
      ],
    },
    {
      name: 'Ayerbe transpaletas - Transpaleta ay-2500-thn ruedas nylon',
      category: 'Transpaletas',
      slug: 'Ayerbe-transpaletas-Transpaleta-ay-2500-thn',
      image: '/images/transpaletas/51aa-CUFuKL._AC_SL1050_.jpg',
      price: 360.0,
      brand: 'Ayerbe',
      rating: 4.4,
      numReviews: 6,
      countInStock: 1,
      description: [
        'Transpaleta manual con capacidad de 2.500 Kgs AY-2500-THN.',
      ],
    },
    {
      name: 'Einhell palé Transpaleta TC de PT 2500 (carga 2500 kg, tenedor Altura 80 – 190 mm, estructura resistente en acero, ruhige unidad eigenschaft el Poco rodadura)',
      category: 'Transpaletas',
      slug: 'Einhell-palé-Transpaleta-TC-de-PT-2500',
      image: '/images/transpaletas/61dkfU2y7IL._AC_SL1500_.jpg',
      price: 388.5,
      brand: 'Einhell',
      rating: 4.2,
      numReviews: 11,
      countInStock: 1,
      description: [
        'Elevador de la paleta robusta para cualquier taller profesional con seguridad autodescargables y integ. palanca de cambios con tres funciones',
        'Retorno automático de la perla en la vertical. fuerza de carga 2500 kg, tenedor, Altura 80 – 190 mm, robusta construcción de acero, tranquilo unidad característica al poco rodadura',
        'Fiable, mantenimiento hidráulica y construcción resistente con acero soldado marco',
        'repujadas, gabelzinken reforzadas para la carga fiable de grabación',
        'Características de funcionamiento tranquilo y bajo rodadura mediante rodamiento de bolas y revestimiento de PU en asiento y arrastre ruedas',
      ],
    },
    {
      name: 'Ayerbe M110167 - Traspaleta 2500 kg ruedas de vulkollan',
      category: 'Transpaletas',
      slug: 'Ayerbe-M110167-Traspaleta-2500-kg-ruedas-de-vulkollan',
      image: '/images/transpaletas/51tUVKou28L._AC_SL1050_.jpg',
      price: 420.0,
      brand: 'Ayerbe',
      rating: 4.8,
      numReviews: 15,
      countInStock: 1,
      description: [
        'Ruedas PU y una capacidad máxima de 2500 kg',
        '4 rodillos de Ø 80 mm 2 ruedas de Ø 200 mm',
        'Válvula de seguridad por sobrecarga y sistema de descenso controlado',
        'Pistón cromado. Normativas: CE, GS y TÜV',
      ],
    },
    {
      name: 'WOLFPACK LINEA PROFESIONAL Transpaleta De Almacen Ruedas Poliuretano 2,5 T.',
      category: 'Transpaletas',
      slug: 'WOLFPACK-LINEA-PROFESIONAL-Transpaleta-De-Almacen-Ruedas-Poliuretano',
      image: '/images/transpaletas/51-a-qhL++L._AC_SL1372_.jpg',
      price: 413.16,
      brand: 'WOLFPACK LINEA PROFESIONAL',
      rating: 0,
      numReviews: 0,
      countInStock: 1,
      description: [
        'Capacidad de carga: 2.5 toneladas.',
        'Estructura de acero especial de alta resistencia.',
        'Timón con barra envolvente de seguridad y diseño ergonómico.',
        'Palanca de maniobra accionada por bomba hidráulica.',
        'Cilindro hidráulico con accesorios antiaceite que aporta estanqueidad del líquido.',
      ],
    },

    {
      name: 'Ayerbe - Apilador manual ay-2500-apm 1000kg',
      category: 'Carretillas Elevadoras',
      slug: 'Ayerbe-Apilador-manual-ay-2500-apm-1000kg',
      image: '/images/carretillasElevadoras/41eqdNt892L._AC_.jpg',
      price: 1645.95,
      brand: 'Ayerbe',
      rating: 0,
      numReviews: 0,
      countInStock: 1,
      description: ['Apilador manual ay-2500-apm 1000kg'],
    },
    {
      name: 'TAP 47004 Apilador manual - fuerza 400kg',
      category: 'Carretillas Elevadoras',
      slug: 'TAP-47004-Apilador-manual-fuerza-400kg',
      image: '/images/carretillasElevadoras/71WsEAIIb9L._SL1500_.jpg',
      price: 0.0,
      brand: 'TAP FRANCE',
      rating: 0.0,
      numReviews: 0,
      countInStock: 0,
      description: [
        'Se levanta con una pedal; se baja con una palanca que permite una maniobra muy precisa; frenos accionados con pedal',
        'Bastidor y horquillas de acero reforzado, acabado pintado epoxi amarillo; bandeja amovible de acero reforzado, tubos cromados',
        'Ruedas de dirección ( diámetro 127x40 mm) de fundición con banda de poliuretano, giran hacia los 360°; ruedecillas de larguero ( diámetro 75x40 mm) de acero con banda de poliuretano',
        'Capacidad de carga: 400 kg.distancia exterior de las horquillas: 576 mm; altura de levantamiento mínima/máxima: 85/1415 mm; medidas de las horquillas (lxanchxalt): 1165x160x50 mm',
      ],
    },
    {
      name: 'APILADOR MANUAL DE 1000KG DE CAPACIDAD 1600MM DE ELEVACIÓN',
      category: 'Carretillas Elevadoras',
      slug: 'APILADOR-MANUAL-DE-1000KG-DE-CAPACIDAD-1600MM-DE-ELEVACIÓN',
      image: '/images/carretillasElevadoras/41IyjGz-2nL.jpg',
      price: 929.0,
      brand: 'Disset elevació',
      rating: 0.0,
      numReviews: 0,
      countInStock: 1,
      description: ['APILADOR MANUAL NUEVO', 'Modelo MX10/16'],
    },
    {
      name: 'Apilador Manual de 1000kg de capacidad y 1600mm de elevación [Clase de eficiencia energética A]',
      category: 'Carretillas Elevadoras',
      slug: 'Apilador-Manual-de-1000kg-de-capacidad-y-1600mm-de-elevación-PRAMAC',
      image: '/images/carretillasElevadoras/41PbOmMMWZL._AC_.jpg',
      price: 929.0,
      brand: 'Pramac',
      rating: 0.0,
      numReviews: 0,
      countInStock: 1,
      description: [
        'Apilador Manual de 1000kg de capacidad y 1600mm de elevación [Clase de eficiencia energética A]',
      ],
    },

    {
      name: 'Intex 28272NP Small Frame - Piscina desmontable, 300 x 200 x 75 cm, 3.834 litros, azul',
      category: 'Piscinas desmontables',
      slug: 'Intex-28272NP-Small-Frame-Piscina-desmontable',
      image: '/images/piscinasDesmontables/71hukYKs-KL._AC_SL1500_.jpg',
      price: 119.0,
      brand: 'Intex',
      rating: 4.6,
      numReviews: 23416,
      countInStock: 1,
      description: [
        'Piscina rectangular desmontable tubular Intex Small Frame con estructura metálica, medidas: 300 x 200 x 75 cm, capacidad: 3.834 litros, para 6 personas (+ 6 años)',
        'Con estructura metálica de fácil montaje, compuesta por piezas de acero con epoxy antióxido, lista para ser usada en aproximadamente 30 minutos',
        'Lona con tecnología tricapa Super-Tough, cuenta con tapón de vaciado conectable a manguera de jardín para facilitar el desagüe',
        'No incluye depuradora pero cuenta con conexiones de 32 mm para poder adaptársela',
        'Recomendadoes para espacios pequeños gracias a su diseño, para una óptima utilización y durabilidad se aconseja seguir las instrucciones del manual',
      ],
    },
    {
      name: 'Bestway Steel ProPool 300x201x66 cm, Stahlrahmenpool Piscina Desmontable Tubular, Azul, 300 x 201 x 66 cm',
      category: 'Piscinas desmontables',
      slug: 'Bestway-Steel-ProPool-Stahlrahmenpool-Piscina-Desmontable-Tubular',
      image: '/images/piscinasDesmontables/71sSvqwsNjL._AC_SL1500_.jpg',
      price: 106.3,
      brand: 'Bestway',
      rating: 4.2,
      numReviews: 162,
      countInStock: 1,
      description: [
        'Fácil montaje para refrescarse en el jardín, la piscina portátil se instala fácil y rápidamente',
        'Muy estable, la piscina rectangular con resistente marco de acero no requiere herramientas para su montaje',
        'Vaciado sencillo, la válvula de drenaje integrada permite vaciar sin complicaciones la piscina desmontable',
        'Para prolongar su duración, la piscina tubular cuenta con un revestimiento anticorrosión',
        'Incluye piscina desmontable rectangular para niños Steel Pro de Bestway y parche de reparación autoadhesivo, material: TriTech, medidas: 300x201x66 cm, azul',
      ],
    },
    {
      name: 'BESTWAY 56283 - Piscina Desmontable Tubular Infantil Mi Primera Piscina 152x38 cm 580 Litros con Válvula de drenaje Marcos Anticorrosión y Parche de Reparación',
      category: 'Piscinas desmontables',
      slug: 'BESTWAY-56283-Piscina-Desmontable-Tubular-Infantil',
      image: '/images/piscinasDesmontables/811Rbi4R9jL._AC_SL1500_.jpg',
      price: 26.88,
      brand: 'Bestway',
      rating: 4.3,
      numReviews: 1458,
      countInStock: 1,
      description: [
        'Muy estable – La robusta piscina es muy estable e indicada como piscina para niños',
        'Montaje sencillo – Esta piscina desmontable tubular es fácil y rápida de instalar y de guardar',
        'Vaciado rápido – Con la práctica válvula de drenaje, la piscina elevada se puede vaciar cómoda y rapidamente',
        'Tamaño – Esta piscina portátil ofrece mucha diversión con menos gasto de agua y a un precio asequible',
        'El envío incluye – Piscina de superficie para niños My First Frame Pool de Bestway y parche de reparación autoadhesivo, edad recomendada: desde 2 años, material: TriTech, medidas: 152x152x38 cm, azul',
      ],
    },
    {
      name: 'Intex Piscina elevada Metal Frame - 6503 litros, 366 x 76 cm',
      category: 'Piscinas desmontables',
      slug: 'Intex-Piscina-elevada-Metal-Frame-6503-litros',
      image: '/images/piscinasDesmontables/61Oi+tLpACS._AC_SL1500_.jpg',
      price: 117.49,
      brand: 'Intex',
      rating: 4.4,
      numReviews: 6638,
      countInStock: 1,
      description: [
        'Piscina desmontable tubular Intex de la línea Metal Frame circular y de estructura metálica, mide: 366x76 cm, capacidad: 6503 litros',
        'De fácil montaje: instalar sobre terrenos nivelados y firmes para una correcta utilización, recomendada para ser utilizada de 4 a 7 personas mayores de 6 años',
        'Lona fabricada con tecnología Super-Tough, con tres capas de material extrafuerte laminadas y estructura de acero resistente pintadas con epoxy antióxido',
        'Incluye: tapón de vaciado que permite conexión a manguera, conexiones para adaptar a la depuradora (no incluye depuradora) y DVD',
        'Estos modelos de piscinas elevadas están listas para ser utilizadas en aproximadamente 30 minutos',
      ],
    },
    {
      name: 'your GEAR XL Piscina Familiar Gris 4x2x1m Piscina con Marco de Acero Piscina Jardín Piscina para niños',
      category: 'Piscinas desmontables',
      slug: 'your-GEAR-XL-Piscina-Familiar-Gris',
      image: '/images/piscinasDesmontables/61HoUL5L8eL._AC_SL1100_.jpg',
      price: 294.95,
      brand: 'your GEAR',
      rating: 4.0,
      numReviews: 47,
      countInStock: 1,
      description: [
        'Piscina rectangular con marco de acero gris para padres e hijos. Piscina ideal para jardín y terraza. Con 396x207x100cm el plato XXL para niñas, niños y adultos ofrece mucho espacio para jugar',
        'Piscina familiar de tejido vinílico reforzado. El armazón tubular está hecho de acero recubierto de polvo. Se dispone de conexiones para una bomba de piscina o un sistema de filtrado y también una válvula de drenaje del suelo.',
        'La construcción de la piscina se realiza de forma rápida y sencilla. No se necesitan herramientas, las varillas de la tubería simplemente se conectan entre sí y el tiempo de montaje es de sólo unos minutos.',
        'Piscina de jardín - sin aire e inflación. Sin cámaras de aire, una piscina es mucho más robusta y menos propensa a daños. Pero por si acaso, se incluye un kit de reparación',
        'Verano, sol, diversión en la piscina. Dimensiones: 396 x 207 cm, altura: 100 cm, profundidad máxima del agua: 90 cm, volumen del agua: 7300 litros, área de instalación requerida: 434 x 233 cm. Superficie del agua:7m²',
      ],
    },
  ],

  categoriesList: [
    {
      name: 'Taladro Percutor',
      image: '/images/taladrosPercutor/71pXagaxQ1L._AC_SL1500_.jpg',
      slug: 'taladro-percutor',
    },

    {
      name: 'Taladros Atornilladores',
      image: '/images/taladrosAtornillador/81Kr8gxqcsL._AC_SL1500_.jpg',
      slug: 'taladro-atornillador',
    },

    {
      name: 'Amoladoras',
      image: '/images/amoladoras/81M6s7FW1uL._AC_SL1500_.jpg',
      slug: 'amoladoras',
    },

    {
      name: 'Lijadoras',
      image: '/images/lijadoras/71rSLwgwSgL._AC_SL1500_.jpg',
      slug: 'lijadoras',
    },

    {
      name: 'Soldadores',
      image: '/images/soldadores/61lpNdFHpdL._SL1500_.jpg',
      slug: 'soldadores',
    },

    {
      name: 'Compresores de aire',
      image: '/images/compresoresAire/71KbeNPd9rS._AC_SL1500_.jpg',
      slug: 'compresores-aire',
    },

    {
      name: 'Carretillas',
      image: '/images/carretillas/71GEg+AaGaL._SL1500_.jpg',
      slug: 'carretillas',
    },

    {
      name: 'Transpaletas',
      image: '/images/transpaletas/31IIr8eqWPS.jpg',
      slug: 'transpaletas',
    },

    {
      name: 'Carretillas Elevadoras',
      image: '/images/carretillasElevadoras/41eqdNt892L._AC_.jpg',
      slug: 'carretillas-elevadoras',
    },

    {
      name: 'Piscinas desmontables',
      image: '/images/piscinasDesmontables/71hukYKs-KL._AC_SL1500_.jpg',
      slug: 'piscinas-desmontables',
    },
  ],
};

export default data;
